[써니] 2단계 재화 미션 제출합니다.
woowacourse/android-shopping-order pull request #31
Opened 2023-06-03 19:51 UTC by inseonyun

안녕하세요 잭슨! 
이번 미션에서 선택한 재화 요소는 포인트입니다!
> 중간에 카드 개념이 있는데 이는 저희가 고려한 주 재화 요소는 아닙니다 

1. Retrofit 통신 시 콜백을 주로 사용하고, 그 콜백 내에서 또 통신을 수행해 이중, 삼중 콜백을 수행하는 구조가 더러 있어 이러한 문제로 PresenterTest 코드가 굉장히 복잡하고 가독성이 떨어집니다. 이러한 문제를 해결하기 위해서는 어떠한 방법이 있나요..? 

2. Retrofit JSON 직렬화 라이브러리 선택
    > 여러 직렬화 라이브러리 중 제가 고민한 라이브러리는 gson, moshi, kotlinx-serialization 입니다. 
    > gson을 택하지 않은 이유는 자바 객체로 직렬화를 수행하기에 Kotlin의 널 안전성과 같은 일부 기능을 지원하지 않을 수 있습니다.
    > moshi와 kotlinx-serialization 이 두 개에서 고민을 했었는데, 이렇다할 주관을 갖지 못한채 kotlinx-serialization를 택하게 되었습니다.
    > 둘 다  Kotlin의 널 안전성을 보장하고, 속도 측면에서도 유의미한 차이가 있다고 이해하진 못했습니다. 또,  kotlinx-serialization은 Multiplatform 프로젝트에서 높은 성능과 강력한 정적 유형 검사를 원하는 경우에 적합하다고 하는데 이는 이번 미션, 우테코 과정을 진행하며 그렇게 와닿지 않는 내용이라 Kotlin에서 지원하는 공식 라이브러리와 Kotlin 직렬화라는 것에 매료되어 선택했던 것 같습니다. 
    > ps. 여러 게시물들을 읽어봤지만 프로젝트, 팀마다 선호하는? 라이브러리가 다르다고 하는데 잭슨은 어떤 라이브러리를 선호하고, 왜 그런가요?

패키지 분리, 도메인 로직 구현 등으로 파일체인지가 많은데
리뷰 잘 부탁드리겠습니다 : )

2023-06-04 15:17 UTC, namjackson requested changes
안녕하세요 써니! 
구현 잘해주셨네요,! 
몇가지 추가적인 코멘트 남겼으니, 확인해주세요! 
변경사항 적용후, 다시 리뷰 요청해주세요!

2023-06-04 15:17 UTC, namjackson commented on app/src/test/java/woowacourse/shopping/presentation/productlist/ProductListPresenterTest.kt
> +        }
slot을 사용한 이유가 있을까요? 
captureLambda 라는 개념도 있으니 확인해도 좋을거같아요! 

mock과 Fake객체는 어떤차이가 있을까요?
 mockk을 활용하지 않고, 재사용가능한 Fake객체를 만들어보면 어떨까요?

2023-06-04 15:17 UTC, namjackson commented on app/src/test/java/woowacourse/shopping/presentation/productlist/ProductListPresenterTest.kt
> +        }
> Retrofit 통신 시 콜백을 주로 사용하고, 그 콜백 내에서 또 통신을 수행해 이중, 삼중 콜백을 수행하는 구조가 더러 있어 이러한 문제로 PresenterTest 코드가 굉장히 복잡하고 가독성이 떨어집니다. 이러한 문제를 해결하기 위해서는 어떠한 방법이 있나요..?

위에서 언급한 captureLambda를 사용할수도 있고, 
mockk은 파워풀하지만, 코드가 길어지는 단점이 있어서, Fake 객체를 활용해봐도 좋을거같아요,
Test 가독성을 위해  Fake 객체같이 TestHelper 클래스를 만들어봐도 좋을거같아요!

2023-06-04 15:17 UTC, namjackson commented on app/src/test/java/woowacourse/shopping/presentation/productlist/ProductListPresenterTest.kt
> +        justRun { view.setLayoutVisibility() }
어떤 용도로 추가된걸가요?

2023-06-04 15:40 UTC, namjackson commented
> 여러 직렬화 라이브러리 중 제가 고민한 라이브러리는 gson, moshi, kotlinx-serialization 입니다.
> gson을 택하지 않은 이유는 자바 객체로 직렬화를 수행하기에 Kotlin의 널 안전성과 같은 일부 기능을 지원하지 않을 수 있습니다.
> moshi와 kotlinx-serialization 이 두 개에서 고민을 했었는데, 이렇다할 주관을 갖지 못한채 kotlinx-serialization를 택하게 되었습니다.
> 둘 다 Kotlin의 널 안전성을 보장하고, 속도 측면에서도 유의미한 차이가 있다고 이해하진 못했습니다. 또, kotlinx-serialization은 Multiplatform 프로젝트에서 높은 성능과 강력한 정적 유형 검사를 원하는 경우에 적합하다고 하는데 이는 이번 미션, 우테코 과정을 진행하며 그렇게 와닿지 않는 내용이라 Kotlin에서 지원하는 공식 라이브러리와 Kotlin 직렬화라는 것에 매료되어 선택했던 것 같습니다.
> 여러 게시물들을 읽어봤지만 프로젝트, 팀마다 선호하는? 라이브러리가 다르다고 하는데 잭슨은 어떤 라이브러리를 선호하고, 왜 그런가요?

저도 써니님의 의견대로, nonNull이나 default값 등의 Kotlin의 지원으로 kotlinx-serialization 를 선호하고 있어요,
각각 장단점이 있으나, 문제가 될법한 부분이 없고, 성능도 체감하기 힘들기 때문에, 성향에 따라 다를거라 생각이 들어요 😄

2023-06-05 02:27 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/presentation/view/order/OrderPresenter.kt
> +    private val orderRepository: OrderRepository,
OrderRepository에서 카드, 포인트에 대한 데이터 load 작업을 한 번에 수행하는 것은 해당 Repository에 너무 많은 책임, 역할을 부여하는 것 같아 분리하였습니다.
또한, 현재는 포인트 조회를 주문 화면에서만 진행하고 있지만, 추후 유저 페이지가 생기거나 더 나아가 상품 상세에서 해당 상품을 구매했을 때의 예상 적립 포인트가 보일 수도 있다 생각해서 각각의 Repsitory를 분리했습니다.
카드 역시 유저 페이지가 생긴다면 해당 유저 페이지에서 카드를 추가 / 삭제 하는 등의 작업을 할 수 있을 것 같아 분리하게 되었습니다.

2023-06-05 03:01 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/respository/cart/CartRepositoryImpl.kt
> +        onFailure: () -> Unit,
API 명세에서 기존에는 Error Message를 전달해주지 않아 잊고 있었는데,
회의 이후(현재) API에서 Error Message를 전달해주는 것을 까먹고 있었네요 하하;;;
onFailure에서 message를 전달 받아 핸들링 하는 방식으로 수정하였습니다.

2023-06-05 08:07 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/respository/cart/source/remote/CartRemoteDataSourceImpl.kt
> +        .create(CartService::class.java)
RetrofitBuilder를 싱글톤으로 관리하고, 이 안에서 CreateService만 호출해서 할 수 있도록 수정하였습니다.

2023-06-05 08:15 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/respository/cart/source/remote/CartRemoteDataSourceImpl.kt
> +                Log.e("Request Failed", t.toString())
onResponse에서 처리해준것처럼 onFailure를 불러 처리하도록 수정하였습니다.

2023-06-05 08:17 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/respository/cart/source/service/CartService.kt
> +        token: String
RetrofitBuilder에서 client 생성 시 interceptor를 추가해 토큰을 지정하도록 수정하였습니다

2023-06-05 08:21 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/respository/recentproduct/RecentProductRepositoryImpl.kt
> +    override fun getRecentProducts(limit: Int, onSuccess: (RecentProducts) -> Unit) {
기능 구현을 먼저 하다보니 놓친 부분이네요 ..!
presetner의 onFailure를 람다로 받아와 넘겨주는 방식으로 수정했습니다.

2023-06-05 08:22 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/model/CartRemoteEntity.kt
>  data class CartRemoteEntity(
아핫;; 네이밍을 어떻게 잡아줘야할지 고민 했었는데 감사합니다 : )

2023-06-05 08:34 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/presentation/view/cart/CartActivity.kt
> +            presenter.calculateTotalPrice()
'체크 상태가 바뀌면 가격의 총합이 변경된다.' 라는 행위로 봤을 때, update 안에 calculate가 있는게 맞는 거 같네요 ㅎㅎ.. (이전에는 update 함수 안에 calculate를 넣게 되면 두 가지 행위를 하게 되는게 아닌가? 라고 생각을 했던 거 같습니다)

2023-06-05 08:38 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/presentation/view/cart/CartActivity.kt
> +            presenter.calculateTotalPrice()
비슷한 흐름을 갖는 cartProductListener에서도 update 함수 내부에서 calculate 할 수 있도록 수정하였습니다

2023-06-05 08:49 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/presentation/view/cart/CartContract.kt
>          fun setEnableLeftButton(isEnabled: Boolean)
감사합니다 ㅎㅎ show로 수정하였습니다!

2023-06-05 08:51 UTC, inseonyun commented
안녕하세요 잭슨!
리뷰 반영을 다 못했지만 시간 내 제출을 위해 현재 작업한 내용까지 반영 후 리뷰요청합니다!
테스트 코드에 대한 피드백은 거의 반영하지 못했고 남겨주신 피드백에서 이모지, 답변 남긴 내용은 리뷰 반영하였습니다!
DataSource 싱글톤 객체 처리 관련 고민하다 시간이 가버렸네요 하핳.....

잘 부탁드리겠습니다 ㅎㅎ

2023-06-06 08:05 UTC, namjackson requested changes
안녕하세요 써니!
몇가지 피드백 적용잘해주셨네요!
마지막 미션이니, 조금더 리팩토링 해봐도 좋을거같아요! 😄

2023-06-06 08:05 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/presentation/view/order/OrderPresenter.kt
> +    private val orderRepository: OrderRepository,
변경에 유연한 코드는 좋지만 👍 , 과하게 정의되지않은일을 미리 준비하게되면 불필요하게 복잡하게되기도합니다!

2023-06-06 08:05 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/respository/RetrofitBuilder.kt
> +class RetrofitBuilder private constructor(
RetrofitBuilder 분리 👍

2023-06-06 08:05 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/presentation/view/orderlist/OrderListActivity.kt
> +    private lateinit var retrofitBuilder: RetrofitBuilder
activity내에서 변수로 들고있을 필요는 없을거같아요!

2023-06-07 18:11 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/respository/product/source/remote/ProductRemoteDataSourceImpl.kt
>                      onFailure()
Util 패키지 내에 최상위 함수로 responseBodyCallback과 responseHeaderLocationCallback 정의하여 중복 로직 최소화 하였습니다 : )

2023-06-08 06:04 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/presentation/view/order/OrderPresenter.kt
> +    private val orderRepository: OrderRepository,
pointRepository의 경우 제거 하고 orderRepository에서 수행할 수 있도록 변경하였습니다.

2023-06-08 06:06 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/respository/cart/source/remote/CartRemoteDataSourceImpl.kt
> +        private const val ERROR_CONNECT = "연결에 실패하였습니다. 다시 시도해주세요"
throwable을 onFailure에 전달하고 onFailure에서 분기처리를 통해 적절한 에러 메시지를 뷰에 띄울 수 있도록 수정하였습니다.
Presenter에서 Android 종속성 Resource에 접근을 하고 있어 좋은 방법은 아니라고 생각되는데, 어떠한 방법이 있을까요..?

2023-06-08 06:40 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/data/model/Server.kt
> +        SUNNY("eWlzMDkyNTIxQGdtYWlsLmNvbToxMjM0"),
sharedPreference에 유저 토큰을 관리하도록 수정하였고, Sealed class token은 제거 하였습니다.
유저 토큰과 관련해서 궁금한 점이 있는데요!
SharedPreference에서 관리하는 것은 개발자에게 쉬운 방법일 수 있으나 보안상 문제가 될 거라고 늘 생각해왔는데요!
실제 상용 되는 서비스에서는 User Token을 어떻게 관리하게 되나요?

2023-06-08 06:47 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/presentation/view/orderdetail/OrderDetailActivity.kt
> +    private lateinit var token: Server.Token
token의 경우 ShredPreference를 통해 관리하도록 하여 매번 전달할 필요성을 줄였습니다.

단, Url의 경우 SharedPreference로 관리할 필요가 있을까? 라는 생각을 하게 되었고,
굳이 Preference를 만들어서 관리하기 보다. 매번 넘겨주는 것이 더 나을 거 같다는 생각을 했습니다. 불필요한 싱글톤 객체 생성은 메모리 관리에 좋지 않다 생각했기 때문입니다.
잭슨의 생각은 어떠신가요? 또다른 방법이 있다면 의견 부탁드려요! : )

2023-06-08 09:01 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/presentation/view/order/OrderActivity.kt
> +            orderRepository = OrderRepositoryImpl(orderRemoteDataSource),
RepositoryFactory에서 Repository를 생성하도록 수정하였습니다

2023-06-08 09:49 UTC, inseonyun commented on app/src/test/java/woowacourse/shopping/presentation/productlist/ProductListPresenterTest.kt
> +        }
slot을 사용했던건 captureLambda라는게 있는지 몰랐었습니다 하하... 알려주셔서 감사합니다 : )

> mock과 Fake객체는 어떤차이가 있을까요?

mock은 기능의 결과를 나타내는 객체로 지금과 같이 기능의 수행 여부를 테스트 할 때 용이합니다.
fake는 기능을 재구현한 객체로 실제 객체와 동일한 역할을 하도록 만들어졌기 때문에 상태를 테스트하기 용이합니다.

2023-06-09 04:53 UTC, namjackson approved these changes
안녕하세요 써니! 
피드백 적용 잘해주셨네요 😄 
재화 미션은 이대로 종료하도록할게요! 
그동안 고생 많으셨습니다 ! 👍

2023-06-09 04:53 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/respository/RepositoryFactory.kt
> +class RepositoryFactory private constructor(context: Context, url: Server.Url) {
Repository 생성에 대한 책임을 분리해주셨네요 👍 
하지만 모든 Repository를 생성해줄때마다 context가 필요한건 아닌거 같아요! 

생성에 대한 책임을 조금 더 분리해보면 어떨까요?
(개인적으로 network, database, repo들의 생성과 관리를 따로따로 해주고, injector역할만 따로 가지고 있어도 좋을거 같단생각이 들어요.)

2023-06-09 04:53 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/model/Server.kt
> +        SUNNY("eWlzMDkyNTIxQGdtYWlsLmNvbToxMjM0"),
여러 방법이 있겠지만,
상용 서비스에서도 암호화가 추가된 SharedPreference를 활용하곤합니다 
(https://developer.android.com/topic/security/data?hl=ko#classes-in-library)

2023-06-09 04:53 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/respository/cart/source/remote/CartRemoteDataSourceImpl.kt
> +        private const val ERROR_CONNECT = "연결에 실패하였습니다. 다시 시도해주세요"
개인적으로는 presenter까지는 sealed나 Exception클래스를 전달하고, 
실제 메시지는 View에서 접근하는 구조를 사용하곤합니다!

2023-06-09 04:53 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/presentation/view/orderdetail/OrderDetailActivity.kt
> +    private lateinit var token: Server.Token
Url 또한 관리되어야할 요소 아닐까요?
개인적으로는 필요한 객체라고 생각이 들어요!
url에 대한 책임이 분산되어있기 때문에, url에 대한 옵션이나 정보가 요구사항이 변경된다면,
모든 activity가 수정되어야하진 않을까요?

2023-06-09 04:54 UTC, namjackson commented
미션진행하는 과정이 의미있는 시간이 되셧길바랍니다! 
고생하셨습니다 !! 남은 일정들도 응원할게요! 😄

2023-06-09 04:54 UTC, merged