[뽀또] 2단계 재화 미션 제출합니다.
woowacourse/android-shopping-order pull request #45
Opened 2023-06-05 08:20 UTC by hyunji1203

토리 안녕하세요!
이번 미션 retrofit을 이용해 서버와 연결하고, 주문하는 기능을 추가했습니다!
주문하기 기능에는 포인트를 선정해 구현했습니다.
처음 retrofit을 써보는 거라 이렇게 layer을 나눠 구현하는 것이 맞는 지는 모르겠지만..
우선 최선을 다해 구현해보았습니다!
레벨 2 마지막 미션 리뷰 잘 부탁드립니다😁

2023-06-06 06:39 UTC, namjackson requested changes
안녕하세요 뽀또 
미션 구현 잘해주셨네요 👍 
몇가지 코멘트들 남겼으니, 확인해주세요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductDataSource.kt
> +        onFailure: () -> Unit,
실패의 이유는 전달될 필요는 없을까요?

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductRemoteDataSource.kt
> +        })
비슷한 코드가 모든 함수에 중복적으로 있어요! 
분리해보면 어떨까요?

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductRemoteDataSource.kt
> +    private val retrofitService = getCartProductByRetrofit(baseUrl)
retrofitService라는 네이밍이 적절할까요?
retrofit을 사용한 서비스라는걸 굳이 표현할필요가 있을까요? 
네트워크모듈이 변경된다면, 이러한 부분들도 함께 변경이 되어야하는 구조네요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductRemoteDataSource.kt
> +    private val retrofitService = getCartProductByRetrofit(baseUrl)
baseUrl,Service 모두 생성자로 주입방식을 고민해봐도 좋을거같아요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductRemoteDataSource.kt
> +                }
실패시 동일하게 onFailure람다가 작동되야하지 않을까요?

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/datasource/order/OrderDataSource.kt
> +        token: String,
모든 요청에 token이 포함되고 있네요! 
자동화할수 있는 방법은 없을까요? 
interceptor 개념을 학습해보셔도 좋을거같아요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/repository/okhttp/CartRepositoryImpl.kt
> +class CartRepositoryImpl(private val service: CartService) : CartRepository {
사용하지 않는 클래스는 제거해주세요 !
깃히스토리에 남기때문에, 과감히 지워주셔도 좋아요

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/repository/retrofit/CartProductRemoteRepository.kt
> +    private val cartProductDataSource = CartProductRemoteDataSource()
CartProductRemoteDataSource를 내부에서 생성해준 이유가 있을까요?
생성시점에 주입하면 어떤점이 좋을까요?

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/repository/retrofit/CartProductRemoteRepository.kt
> +        get() = ShoppingApplication.pref.getToken()
싱글턴객체에 직접 접근하게 된다면, 결합도가 강하게 생기는 구조가 됩니다.
싱글턴 객체에 대한 직접 접근은 피해주세요.
ShoppingApplication가 아닌 token관리하는 책임을 가지는 클래스를 만들어 보셔도 좋을거같아요,

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/dto/Product.kt
> +    val price: Int,
서버 api 명세서는 약속이지만,
api 명세서의 스펙이 변경되거나, 약속대로 오지않는경우들이 많아요,
만약 name등의 값이 포함되지 않거나, null값이나 빈값이 온다면 어떤현상이 일어날까요?

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/ui/order/history/recyclerview/adapter/loadmore/LoadMoreAdapter.kt
> +class LoadMoreAdapter
불필요한 사용하지 않는 코드들이 많아요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderActivity.kt
> +            cartProducts = intent.getParcelableExtraCompat(CART_PRODUCTS_KEY)!!,
!! 은 언제나 사용을 지양해주세요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderActivity.kt
> +                    val discountPoint = binding.pointEditText.text.toString().toInt()
Int가 아닌값이 들어오면 에러가 나네요,
숫자만 입력할수 있도록 해보아요

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderActivity.kt
> +                    presenter.calculateFinalPayment(discountPoint)
discountPoint 을 입력하지 않으면, 결제금액이 null이 뜨고있네요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderPresenter.kt
> +            onFailure = { },
실패의경우에도, 유저에게 알려주면 좋을거 같아요!

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/util/bindingadapter/TextViewBindingAdapter.kt
> +@BindingAdapter("bind:order_id")
카멜케이스를 사용해주세요 😄

2023-06-06 06:39 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/util/collection/DistinctList.kt
> +class DistinctList<E> : ArrayList<E>() {
중복되지 않는 리스트를 생성해주셨네요,
하지만, 이미 구현된 컬렉션을 사용해보면 어떨까요?

> Iterable<T>.distinct()

2023-06-06 06:39 UTC, namjackson commented on domain/src/main/java/woowacourse/shopping/domain/repository/ProductRepository.kt
>  interface ProductRepository {
데이터 레이어의 테스트 코드도 작성해보면 좋을거같아요

2023-06-08 06:41 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductDataSource.kt
> +        onFailure: () -> Unit,
실패의 이유를 사용자에게 보여줘야 하기 때문에 실패의 이유가 전달되어야 된다고 생각합니다. 따라서 에러 메세지를 `onFailure` 함수에게 전달이 되고, 해당 메세지를 로그로 출력해 사용자가 볼 수 있도록 수정하였습니다!

2023-06-08 07:02 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductRemoteDataSource.kt
> +    private val retrofitService = getCartProductByRetrofit(baseUrl)
적절한 네이밍이 아닌 것 같습니다! 굳이 어떤 것을 사용하고 있는지 명시해줄 필요가 없기 때문입니다. 따라서 각 dataSource 클래스에서 사용하는 service의 변수명을 retrofit을 붙이는 변수명이 아닌 해당 클래스와 관련된 객체를 붙이는 것으로 네이밍을 변경했습니다!
(ex) `cartProductService`, `orderService`, `pointService`, `productService`)

2023-06-08 19:53 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/repository/okhttp/CartRepositoryImpl.kt
> +class CartRepositoryImpl(private val service: CartService) : CartRepository {
넵! 삭제했습니다!

2023-06-08 19:57 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductRemoteDataSource.kt
> +    private val retrofitService = getCartProductByRetrofit(baseUrl)
넵! `DataSource`클래스들이 생성 될 떄 Service를 해당 클래스의 생성자로 받도록 수정하였습니다!

2023-06-08 20:06 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/repository/retrofit/CartProductRemoteRepository.kt
> +    private val cartProductDataSource = CartProductRemoteDataSource()
생성 시점에 `CartProductRemoteDataSource`를 주입하게 된다면 
의존성을 외부로부터 주입받을 수 있게 됩니다. 따라서 이 덕분에 테스트 용이성을 높일 수 있고, 다른 데이터 소스로의 전환이나 교체에도 유연하게 대응할 수 있습니다. 이 뿐만 아니라 나중에 다른 종류의 데이터 소스를 추가하거나 다양한 데이터 소스를 동시에 사용하는 확장성을 보장받을 수 있습니다! 따라서 해당 이점들로 인해 생성 시점에 생성자로 주입받도록 수정하였습니다!

2023-06-08 20:08 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/datasource/cart/CartProductRemoteDataSource.kt
> +                }
네 맞습니다! 해당 부분에 onFailure 함수를 넣는 것을 놓친 것 같습니다. 따라서 람다가 작동되도록 추가하였습니다~!

2023-06-08 20:18 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderPresenter.kt
> +            onFailure = { },
넵! Toast와 Log를 통해 사용자에게 알려주도록 수정하였습니다!

2023-06-08 20:29 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/util/bindingadapter/TextViewBindingAdapter.kt
> +@BindingAdapter("bind:order_id")
넵!

2023-06-08 21:03 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderActivity.kt
> +                    val discountPoint = binding.pointEditText.text.toString().toInt()
숫자만 입력할 수 있도록 해당 editText 뷰에  android:inputType="number" 를 적용시켰습니다

2023-06-08 21:28 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderActivity.kt
> +                    presenter.calculateFinalPayment(discountPoint)
null이 뜨지 않도록 수정했습니다!

2023-06-08 21:35 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/dto/Product.kt
> +    val price: Int,
그렇다면 아마 name의 값이 포함되지 않은 상황에서는 datasource 단에서 데이터를 받아올 때 오류가 날 것 같습니다. 그런 상황이 생겼을 때 retrofit call 안에서 이미 에러 메시지를 띄우도록 하고 있어 해당 에러 메세지를 통해 확인하면 될 것 같다는 생각이 듭니다..! 
반면 null 값이나 빈 값이 오는 상황이라면 앱 내에서 오류가 발생해 터질 것 같습니다. 
그렇다면 이런 상황을 대비해 Dto 클래스들은 nullable한 값으로 지정을 해주는 것이 맞을까요..? 
실례가 되지 않는 다면 API 명세서 대로 오지 않는 경우에 리뷰어님 께서는 어떤 방식으로 처리를 해주시는 여쭤보고싶습니다!

2023-06-08 21:51 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/datasource/order/OrderDataSource.kt
> +        token: String,
interceptor를 적용시켜 중복 코드를 삭제하였습니다!

2023-06-08 22:04 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/ui/order/main/OrderActivity.kt
> +            cartProducts = intent.getParcelableExtraCompat(CART_PRODUCTS_KEY)!!,
넵! !!을 사용하지 않도록 수정했습니다!

2023-06-08 22:10 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/util/collection/DistinctList.kt
> +class DistinctList<E> : ArrayList<E>() {
넵! 수정했습니다

2023-06-08 22:28 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/data/repository/retrofit/CartProductRemoteRepository.kt
> +        get() = ShoppingApplication.pref.getToken()
TokenManager이라는 token 관리 객체를 생성하려고 했습니다! 
하지만 생성하던 도중, `RetrofitUtil`안의 `okHttpAuthClient`에게 token을 넘겨줄 때 문제가 발생했습니다. 
클래스에게 context를 넘겨줘야 preference를 사용할 수 있기 때문입니다... 
하지만 retrofitUtil 클래스 내에서는 context를 넘겨주지 못하므로 클래스를 사용하지 못하게 되었습니다... 
이런 상황에서는 어떻게 이 문제를 해결해야할까요..? 제 스스로 해결하지 못하고 여쭤봐서 죄송합니다....😢 이런 상황에서도 ShoppingApplication을 쓰면 안되는 걸까요..?

2023-06-09 08:09 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/util/RetrofitUtil.kt
> +    }
okHttpClient와 별도로 가지고 있을 필요는 없을거같아요,
tokenManager에서 token이 있을때만 헤더를 추가하면 좋을거같아요!

2023-06-09 08:12 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/data/dto/Product.kt
> +    val price: Int,
개인적으로는 Gson을 사용하셨다면, response에 대한  값들은 nullable한 값을 지정해주는 방식도 좋을거 같단 생각이 들어요! 
nonNull한 변수라도 null인 경우가 있기때문에, 예측하기가 힘듭니다

2023-06-09 08:15 UTC, merged