Step2
woowacourse/android-shopping-order pull request #48
Opened 2023-06-05 08:35 UTC by s9hn

ㅇㅇ

2023-06-06 03:03 UTC, vagabond95 commented
>  새로운 Thread를 열고 해당스코프내에서 서버통신을 하게되면 단적으로 봤을 때 enqueue와 무슨 차이인지 모르겠습니다!

말씀하신 것처럼 새로운 실행흐름(Thread) 에서 로직이 수행된다는 점은 큰 차이점이 없습니다.
차이점이 생기는 지점은 Thread 를 관리하는 지점입니다.

Thread 는 생각보다 비싼 자원을 요구합니다. 그래서 Thread 를 재활용할 수 있는 ThreadPool 과 같은 구조가 나오게 된 것이구요! 그래서 직접 Thread 를 생성하고 이용한다면, 이를 효율적으로 사용하는데 많은 작업이 요구됩니다.
또한, Thread 가 언제 시작될지, 언제 종료가 될지, 예외가 발생하면 어떻게 종료를 시킬지 등 신경써줘야할 부분이 많습니다.

이로인해 추상화의 관점으로, '너가 내부에서 Thread 를 어떻게 사용하는지는 모르겠고 나는 수행되어야하는 로직만 작업할 것이다.' 라는 식의 구현이 enqueue 등을 이용한 것이라고 볼 수 있겠습니다.

2023-06-06 03:04 UTC, vagabond95 requested changes
안녕하세요 산군! 마지막 미션 진행하시느라 고생 많으셨습니다 👍 

질문 주신 내용 및 구현 내용을 바탕으로 코멘트 남겼어요!
이를 바탕으로 같이 논의 진행해보면 좋겠습니다 :)

2023-06-06 17:03 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/utils/RetrofitExtension.kt
> +    onError: ((throwMessage: Throwable) -> Unit)? = null,
다시보니 각각의 이름을 좀 더 구체적으로 명시할 필요가 있겠군요!!
해당 코드에서 onError는 서버통신자체가 되지 않았을 경우이고
onFailure는 통신은 되었으나 정상적으로 데이터를 불러오지 못한 경우입니다!

2023-06-06 17:33 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/ui/order/OrderActivity.kt
> +            val orderItems = cartItems.cartProducts.map { it.id.toInt() }
오 ㅋㅋ 저도 제출하고 해당코드에서 똑같이 생각하고 바로 프레젠터로 옮겼습니다!

2023-06-06 17:37 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/ui/order/presenter/OrderPresenter.kt
> +            onFailure = { Log.d("ERROR_OrderPresenter", it.toString()) },
해당 부분에 동의합니다! 
저 또한 에러에 대해 토스트메시지 혹은 다이얼로그 등 대응이 필요하다고 생각해, 해당 에러메시지를 프레젠터까지 끌고 온 이유입니다!
다만 현재 앱에서 어떤식으로 에러를 대응해줄지에 대한 고민은 후순위인 것 같아 로그정도만 남겨두었습니다!

2023-06-08 19:28 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/data/remote/api/OrderService.kt
> +    ): Call<List<CouponsResponseDto>>
``` kotlin
class CouponsDto : ArrayList<Coupon>

data Class CouponsDto(
     val data: List<Coupon>
) {
      data class Coupon(
         val property : Property
          ...
      )
}
```
해당 부분을 구현할 때, 리스폰스 리턴타입때문에 진짜로 새벽에 3시간정도 시간을 쓴 것 같습니다.. 처음엔 저도 위 코드처럼 해당 리스트를 묶는 Dto를 만들기도 했고, dataClass 변환 플러그인을 사용하여 시도를 해보았는데도 불구하고 
> kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $

계속 위와 같은 에러를 만났는데, 구글링과 지피티를 아무리 뒤져도 뭐가 문제인지 못찾았다가, 결국 현재 코드처럼 List로 감싼형태를 하니까 직렬화가 되었습니다..

해당부분을 다시 시도해보려했는데, 현재 서버가 닫혀있는 상태라 리팩터링을 진행하지 못하였습니다.

표현방식을 하나로 통일할 생각은 못했었는데, 다음부턴 일관된 표현방식으로 리스폰스를 전달해보겠습니다!

2023-06-08 19:31 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/data/remote/api/OrderCompleteService.kt
> +        @Header("Authorization") token: String,
인터셉터를 사용하여, 헤더추가를 자동화해주었습니다. 다만 현재구조가 조금 불편한게
레트로핏 객체를 생성해주는 오브젝트 내에서 인터셉터의 객체를 생성해주고 있습니다.
문제는 헤더에 들어갈 토큰값은 sharedPreference의 구현체에 있으며, 이 구현체를 오브젝트 내의 인터셉터에게 주입해주어야만 합니다. 이 과정에서 오브젝트에서 컨텍스트를 호출해야하는 일이 생겨버려서, 해당부분을 의존성 주입이 아니고서 어떻게 해결해야할 지 잘 모르겠습니다! 

현재는 앱 전역에서 사용 될 서버객체이자 헤더값이기에 Application Context를 넣어주는게 그리 문제가 될 것 같지는 않다고...생각은 했습니다.

2023-06-08 19:39 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/data/datasource/remote/order/OrderDataSourceImpl.kt
> +            onFailure = { onFailure.invoke(FAIL(Disconnect(it))) },
서버로부터 데이터를 정상적으로 호출하지 못하는 경우
DisabledDataCall(서버에서주는메시지)를 넘겨주도록 수정하였습니다

2023-06-08 19:40 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/utils/RetrofitExtension.kt
> +    onError: ((throwMessage: Throwable) -> Unit)? = null,
좀 더 구체적으로
onFailInitServer와 onFailFetchData로 변경해주었습니다.

2023-06-08 19:47 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/data/datasource/remote/producdetail/ProductDetailSourceImpl.kt
> +        }.get()
페어의 코드여서 제가 수정하기엔 너무 많은 리소스가 필요할 것 같아 우선순위를 후순위로 두었습니다ㅠㅠ..
아마 당장 시간이 급해서 예외처리를 따로 신경쓰지 않고 진행한 것 같습니다!
개인적으로, 안드로이드 내에서 예외를 던지는 건 지양해야한다고 생각합니다.
유저가 앱을 사용하면서 어떠한 이유로도 앱이 슛아웃되는 현상은 피해야할 것 같습니다.

그래서 예외처리방법으로 null 혹은 result객체를 반환하여, 분기처리를 해주거나 혹은 암시적인 방법으로 -1과 같은 매직넘버를 보내주는 식으로 대응할 것 같습니다!

2023-06-08 19:49 UTC, s9hn commented on app/src/main/java/woowacourse/shopping/data/remote/api/ShoppingCartService.kt
> +    ): Call<Void>
Void는 자바와의 호환성, Unit은 코틀린과의 호환성으로 알고 있습니다.

본 부분도 페어와ㅎㅎ;; 상의해보고 피드백해보겠습니다!

2023-06-08 19:52 UTC, s9hn commented
구현 마무리와 리팩터링을 진행하며 궁금한점 대댓글?로 남겨두었습니다!
현재 서버가 닫혀있어서 테스트진행을 못했습니다.. 죄송합니다🥲

마지막날까지 리뷰에 시간내주셔서 감사합니다. 좋은하루 되세요 !

2023-06-09 15:07 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/datasource/remote/producdetail/ProductDetailSourceImpl.kt
> +        }.get()
result 에서 제공하는 [runCatching](https://medium.com/harrythegreat/kotlin-runcatching%EA%B3%BC-result-%ED%83%80%EC%9E%85-ab261f47efa8) api 를 활용해봐도 좋겠습니다~!

2023-06-09 15:08 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/datasource/remote/order/OrderDataSourceImpl.kt
> +            onFailure = { onFailure.invoke(FAIL(Disconnect(it))) },
disconnect 는 연결이 끊겼다는 맥락만 전달주기 때문에,
말씀해주신 수정사항이 좀 더 직관적인 것 같습니다~!

2023-06-09 15:11 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/remote/api/OrderCompleteService.kt
> +        @Header("Authorization") token: String,
말씀해주신 것처럼 application context 자체가 전역적으로 활용하라고 만든 것이기 때문에 큰 문제가 되지는 않을 것 같아요.

다만, 그럼에도 불구하고 retrofit 을 다루는 모듈은 data layer 이므로 다른 layer 에서 sharedPreference 를 통해 값을 받고, 이를 넘겨주는 방식으로 하면 좀 더 코드가 android 에 의존적이지 않고 유연한 구조를 가져가게 되겠죠 :)

2023-06-09 15:12 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/remote/api/OrderService.kt
> +    ): Call<List<CouponsResponseDto>>
이 부분, 제가 서버 스펙을 확인해보니 
애초에 서버쪽에서 json 을 감쌀 때 한번더 감싸주지 않고 바로 List 레벨로 던져주고 계시더라구요. 
이부분은 어쩔 수 없이 따라갈 수 밖에 없는 것 같습니다. 😢 

다만, 실무 레벨에서는 통일성 있는 구조를 위해 서버쪽에 규격을 맞춰달라고 요청드릴 수 는 있어보여요!

2023-06-09 15:15 UTC, vagabond95 commented
MVP, MVVM 등의 아키텍처와 data layer 등이 어느 레벨까지 구현되어야하는지 감을 잡기 어려운 경우,
오픈소스를 참고해보시는 것도 좋습니다.

개인적으로 [nowinandroid](https://github.com/android/nowinandroid) 추천드려봅니다 :)

2023-06-09 15:16 UTC, vagabond95 approved these changes
리뷰 사항 모두 잘 반영해주셨네요 👍 
질문 주셨던 내용은 하위 코멘트로 남겼습니다!

미션 마무리하도록 하겠습니다.
그동안 정말 고생많으셨습니다. 나중에 또 뵐 수 있는 기회가 있었으면 좋겠습니다 :)

2023-06-09 15:16 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/remote/AuthInterceptor.kt
> +            .addHeader("Authorization", authInfoDataSource.getAuthInfo() ?: NO_TOKEN)
interceptor 구조 잘 잡아주셨는데요 ?! 👍

2023-06-09 15:16 UTC, merged