[쇼핑 주문] 악어 1, 2 단계 미션 제출합니다.
woowacourse/android-shopping-order pull request #53
Opened 2024-05-30 08:10 UTC by Hogu59

두루 안녕하세요,
악어입니다! 🐊 

처음 배우는 것이 많아 난관이 조금 있었는데, 기간에 정함이 있어 구현 중심주의로 진행했습니다....
부족한 테스트와 터지는 에러들은 리팩토링 하면서 추가/보완 하도록 하겠습니다!

리뷰 잘 부탁드립니다! 🙇‍♂️

2024-05-30 12:54 UTC, Gyuil-Hwnag requested changes
악어 안녕하세요!
레벨1에 이어 레벨2 마지막 미션을 함께하게 된 두루라고 합니다. 잘부탁드립니다!

해당 미션 구현 고생 많으셨습니다!
미션 구현을 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.
아직 구현과 코드 정리가 덜 된 부분들이 조금 있는 것 같다는 생각이 들었습니다🥲
다음 요청때는 잘 다듬어 지시리라 믿겠습니다💪

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
마지막 미션 화이팅입니다!!

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/build.gradle.kts
> +    implementation("com.squareup.retrofit2:retrofit:2.11.0")
스켈레톤 Ui에 대해서 shimmer를 사용하셨군요~👍
해당 라이브러리를 사용하신 이유에 대해서 악어의 의견을 자유롭게 남겨주세요!
라이브러리를 사용하면, 물론 간편하기는 합니다 다만, 라이브러리를 사용함으로서 얻게 되는 단점들은 어떤 것들이 있을까요??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/androidTest/java/woowacourse/shopping/DetailActivityTest.kt
> +        )
테스트 코드 너무 잘 작성해주셨네요~👍
더미 데이터등을 만들어서 실제 데이터가 Ui에 잘 반영되는지도 테스트 해보면 어떤가 라는 생각이 듭니다🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/androidTest/java/woowacourse/shopping/ShoppingActivityTest.kt
> +        )
해당 내용도 다음 요청에는 잘 적용해주시리라 믿겠습니다~💪

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true"
해당 내용들을 넣으면 어떤 동작을 할까요??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +            .addConverterFactory(GsonConverterFactory.create())
수정이 필요한 것은 아니며, 추후를 위해서 고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!
git public repository로 프로젝트를 올릴 때 baseUrl 같은 경우에는 공개가 될 경우 추후 서비스에 많은 영향을 미칠 수 있는데, 해당 URL등은 어떻게 관리를 하는 방법들이 있을까요??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +            }
해당 내용은 어떤 것을 의미할까요??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +                response =
해당 부분에서 CoroutineScope 로 처리해주신 이유가 있을까요??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +        private val email = "hogu59"
`AppInterceptor`를 `ProductClient` 내부에 구현하신 이유가 있을까요??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +        private val password = "password"
위에 BASE_URL에 남겨둔 내용에 추가적으로 이런 키값들은 따로 분리를 해보는 것은 어떨까 라는 생각이 듭니다!💪

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/database/product/MockProductService.kt
> +                .build()
`MOCK_SERVER_URL` 라는 상수를 활용해보는 것은 어떨까 라는 생각이 듭니다!🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/repository/CartRepositoryImpl.kt
> +    private val dao = ShoppingDatabase.getInstance(context).cartDao()
해당 `CartRepositoryImpl` 는 현재 따로 사용을 안하고 있는 것처럼 보여지는데, 다음 요청에서 구현이 추가될 내용들이 맞을까요..??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/repository/CartRepositoryImpl.kt
> +    }
`Thread`에 동작에 대해서 함수로 만들어두셨군요~👍
위에 `Intercepter` 에서는 Coroutine을 사용하고 여기서는 thread 를 사용하셨는데, 비동기 처리에 대해서 하나로 통합을 해서 사용을 해보는 것도 좋을 것 같다는 생각이 듭니다!💪

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingItemsRepositoryImpl.kt
> +) : ShoppingItemsRepository {
해당 부분은 아직 구현이 덜 끝난 것 같이 보이는네요🥲

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/domain/repository/RecentProductRepository.kt
> +    fun loadSecondLatest(): RecentProduct?
해당 함수의 결과를 Result 객체로 매핑을 해보는 것은 어떨까 라는 생각이 듭니다!🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartClickListener.kt
> +}
인터페이스가 무수히 많이 분리가 되어 있는 것 같아보이는데, 이를 통합해 보도록 해보는 것은 어떨까 라는 생각이 듭니다🤔
recommendationActionHandler, selectionHandler, 등등으로요!
추후 재사용등을 위해서 분리하셨다면 수정을 안하셔도 됩니다!
다만 그럴경우 분리를 해주신 기준에 대해서 악어의 의견을 남겨주세요~

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +                    }
해당 경우에 대해서는 UiState.Loading을 만들어서 두고 init 블록에서 값을 넣어주도록 해보는 것은 어떨까 라는 생각이 듭니다!🥲

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +                Log.d("crong", "setupState")
해당 ViewModel 에서 Log 가 많이 보이네요😅

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendationFragment.kt
> +        }
DataBinding을 활용해보는 것은 어떤가 라는 생각이 듭니다!🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/selection/SelectionFragment.kt
> +    }
해당 내용들도 DataBinding을 활용해 볼 수 있겠다는 생각이 듭니다~💪

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivity.kt
> +        }
해당 구현은 어떤 기능을 할까요??🤔

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingAdapter.kt
> +        notifyDataSetChanged()
RecycelrViewAdapter 에는 notifyXXX등 여러가지 함수가 있을텐데, `notifyDataSetChanged()`로 하면 어떤 동작을 하게 되며, 어떤 단점이 있을까요??🤔
악어의 의견을 자유롭게 남겨주세요~

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingAdapter.kt
> +    private var products: List<Product> = emptyList()
이전 미션에서 RecyclerViewAdapter 에 대해서 많은 것을 살펴보셨을텐데, 이번 미션에서 ListAdapter로 마이그레이션을 진행해보는 것도 좋을 것 같다는 생각이 듭니다!💪

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_cart.xml
> +                android:padding="10dp"
DataBinding의 활용 좋습니다~👍

2024-05-30 12:54 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_cart.xml
> +            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
BindingAdapter의 활용 좋습니다~👍

2024-05-31 05:44 UTC, Hogu59 commented on README.md
> +- I trust the server will not return null type in this project
신뢰기반의 우테코, 서버 개발자를 신뢰합니다 ㅋㅋㅋ 😄

2024-05-31 05:59 UTC, Hogu59 commented on app/build.gradle.kts
> +    implementation("com.squareup.retrofit2:retrofit:2.11.0")
일단 shimmer를 사용했을때,
장점은 로딩 화면에서 애니메이션을 손쉽게 사용할 수 있다는 장점이 있다고 생각합니다.
물론 직접 구현으로도 가능하고, 스켈레톤 ui 라는 지점에서 애니메이션이 필수적인 요소는 아니니 shimmer ui 를 굳이 사용하지는 않아도 무방하지만, 애니메이션 효과 자체는 ux 측면에서 로딩을 덜 지루하게 느끼게 만든다는 점에서 상당한 장점이 있다고 생각합니다.

> 라이브러리를 사용하면, 물론 간편하기는 합니다 다만, 라이브러리를 사용함으로서 얻게 되는 단점들은 어떤 것들이 있을까요??🤔

라이브러리 사용에 대한 단점으로 생각해보면,
1) 라이브러리에 대한 의존이 먼저 생각나네요.
- 라이브러리 업데이트에 따른 버전 호환성의 문제도 고려해볼만 하고
- 특정 일부 기능의 수정에 있어서도 원하는 대로 수정하지 못하는 단점이 생길 수 있겠네요
- 이건 가능할지 모르겠지만, 라이브러리가 이제 더이상 지원하지 않고, 기존에 했던 배포 내용마저도 없애버린다면 구동중인 서비스에서 해당 내용들을 모두 걷어내야할 수도 있지 않을까 싶습니다. 🤔 

2) 라이브러리가 충분히 비대하다는 전제하에 리소스를 불필요하게 잡아먹을 수 있다는 것도 고민해볼 법 하네요.
- 사용하지 않는 기능을 위해 리소스를 할당해줘야하거나
- (사용하지 않을 코드를 작성하는것도 들어가는 리소스로 고려해볼수도 있겠군요)
- 원하는 내용 이외의 것을 위해 메모리를 사용하게 된다면 성능저하가 발생하는 것도 고려볼 수 있을 것 같습니다!


다만, 여기서는 shimmer ui 자체가 크지 않다고 생각했고, 사용함으로써 얻는 이익이 더 크다고 생각해서 사용 하는 것으로 결정했습니다!

2024-05-31 06:09 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +            .addConverterFactory(GsonConverterFactory.create())
따로 파일을 뺀 다음에 `.gitignore`를 사용하는 방법이 있겠군요!
그리고 따로 뺀 파일의 값을 참조해서 쓰면 될 것 같습니다! 🤔  😄

2024-05-31 06:32 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +                Log.d("crong", "setupState")
Log 를 안 지우고 올려서 죄송합니다! 보시는데 불편하셨을것 같네요!
Log 라인들 모두 삭제했습니다! 🙇‍♂️

2024-05-31 09:16 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +            .addConverterFactory(GsonConverterFactory.create())
암호화할 정보에 대해서는 `local.properties`에 넣어 두겠습니다!

2024-06-01 03:36 UTC, Hogu59 commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true"
`android:exported="false"`는 다른 앱에서 해당 컴포넌트에 액세스 할 수 없게 만든것입니다.
 -> 해당 앱에서 다른 앱에서의 접근이 필요하지 않으므로 false로 설정했습니다.

`android:noHistory="true"`는 액티비티가 백스택에 남지 않도록 하는 설정입니다. 즉 다른 액티비티로 갔다가 뒤로가기(백버튼 클릭)를 할 때,  스택에 저장된 액티비티가 없으니 아예 앱을 나가게 되는 것이죠.

2024-06-01 03:48 UTC, Hogu59 commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true"
![image](https://github.com/woowacourse/android-shopping-order/assets/62333909/b5718f5c-fc8f-4060-a32e-d6c3c94da216)

`noHistory="true"` 설정을 할 때, 단점이 먼저 떠오르는데요,
1) OnBackpressed에 대한 함수 오버라이딩을 해두지 않으면, 엄밀하게는 백버튼 클릭에 대한 내용을 구현해놓지 않는다면 중간에 백버튼을 눌렀을때 앱이 꺼지는 상황을 만들게 될 수 있습니다.
2) 액티비티를 계속해서 만들어 사용하다보니, 리소스를 많이 잡아먹을 수 있을 것 같습니다.

다만, 장점을 고려해본다면,
어떤 행위, 백버튼 클릭이 될 수도 있고, 상단의 카트 이미지뷰, 혹은 액션바의 "X" 이미지가 될수도 있겠죠. 이런 버튼 클릭이 다양한데, 각각의 버튼 클릭에 따른 작동이 다르다고 할때, 구현이 좀 더 용이할 수 있을 것 같습니다. 요약하자면, 코드 작성의 용이성일 수 있을것 같습니다.

하지만 적으면서 생각해보니, 필요한 액티비티는 남겨두고, 필요없는 것들은 스택에 쌓지 않는것을 명시적으로 사용할때, 최적화된 모습이 될 것 같다는 생각이 드네요!

2024-06-01 05:47 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +                response =
비동기 처리에 대해서 잘 알지 못하다 보니 이것저것 중구난방으로 사용했습니다.. 😓
해당 내용 삭제처리하도록 하겠습니다!

2024-06-01 05:51 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +        private val email = "hogu59"
이것도 역시 처음 하다보니 해당 내용도 `ProductClient`안에 작성했던 것 같습니다.
내부에 작성한 이유는 안에서 `Interceptor`를 사용하다보니, 내부에 구현하게 되었습니다!

현재는 해당 내용 분리 해두었습니다!

2024-06-01 13:40 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +        private val password = "password"
해당 local.properties로 옮겨두었습니다!

2024-06-01 23:55 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/database/product/MockProductService.kt
> +                .build()
오 그렇네요, 기존 상수 활용하도록 변경했습니다.

2024-06-02 01:16 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +            }
해당 내용은 response 가 null이 아닐때까지 기다리게 만들었던 것 같은데, 불필요한 내용이라 삭제 처리 했습니다!

2024-06-02 01:19 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/repository/CartRepositoryImpl.kt
> +    }
비동기 처리에 대해 처음 공부하다 보니 중구난방으로 사용했네요..ㅎㅎ 😅 
해당 내용 `latch`를 사용하는 로직으로 통합했습니다!

2024-06-02 01:24 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/repository/RecentProductRepositoryImpl.kt
> +    }
해당 내용 latch를 사용하는 로직으로 통합했습니다!

2024-06-03 05:38 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingAdapter.kt
> +        notifyDataSetChanged()
`notifyDataSetChanged()`를 사용하게되면, 모든 변동에 대해서 한번에 처리할 수 있습니다.
아이템의 순서변경, 아이템 그 자체의 데이터 변경 등의 모든 변동에 대해서 한번에 처리할 수 있습니다만,
단점으로는 불필요한 작업까지도 같이 수행하게 되어 어플리케이션 퍼포먼스가 떨어지게 되거나, 모든 아이템을 업데이트하게 되어 UI가 깜빡거리게 되는 등 효율 및 UX적으로는 좋지 않은 사용방법이긴 합니다.

IDE에서도 `notifyDataSetChanged()` 사용을 최대한 지양할 것을 warning으로 알려주고 있습니다만, 이번에는 구현 중심으로 진행하다보니, 해당 내용에 대해서 알면서도 수정을 못했네요...ㅎㅎㅎ

해당 내용은 ListAdapter를 상속받아 사용하면서 수정하도록 하겠습니다! 😄

2024-06-04 05:03 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/repository/CartRepositoryImpl.kt
> +    private val dao = ShoppingDatabase.getInstance(context).cartDao()
다음에 추가될 내용이라기보다는, 이전 local 저장소입니다. Local Repository는 현재 사용하지 않으므로 삭제 처리하겠습니다!

2024-06-04 05:05 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +            if (cartItemData != null || response?.code() != 200) {
해당 내용도 latch를 사용하는 로직으로 변경한 후 삭제처리하였습니다!

2024-06-04 05:09 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +        val limit = pageSize
해당 내용 사용 안하고 있네요...ㅎㅎ
삭제처리하였습니다! 😅

2024-06-04 05:27 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingAdapter.kt
> +    private var products: List<Product> = emptyList()
첫 화면의 상품 목록을 보여주는 화면과 최근 본 상품을 보여주는 recyclerView 2개에 대하여 ListAdapter로 마이그레이션을 마쳤습니다.
CartActivity에서 관리하는 장바구니 상품 목록, 추천상품 목록 두개에 대해서도 마이그레이션을 진행해보았는데, 조금 더 시간이 걸릴 것 같습니다. 해당 내용은 다음 미션 진행하면서 수행해보도록 하겠습니다!

2024-06-04 05:29 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivity.kt
> +        }
viewModel의 products 즉 상품 목록 정보를 recyclerView 의 adapter에 전달하고, 전달하는 동안 문제가 생길 경우, 오류 메세지를 토스트로 띄우는 기능을 구현하고자 만들었습니다!

2024-06-04 06:45 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendationFragment.kt
> +        }
Databinding 활용하여 처리하도록 변경했습니다!

2024-06-04 06:46 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/selection/SelectionFragment.kt
> +    }
Databinding 활용하여 처리하도록 변경했습니다!

2024-06-04 11:35 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartClickListener.kt
> +}
CounterHandler는 같은 내용을 계속 사용하고 있어 통합하면 좋을것 같네요.
해당 내용 통합하였습니다.

다만 eventHandler의 경우 각 액티비티나 프래그먼트에 대한 `eventHandler`는 따로 남겨두었습니다. 액티비티와 프래그먼트 뷰모델에서 상속받을 Handler가 필요해서 남겨두었습니다,.

2024-06-04 11:45 UTC, Hogu59 commented on app/src/androidTest/java/woowacourse/shopping/DetailActivityTest.kt
> +        )
UiTest에서 ViewModel에 더미 데이터를 넣는 방법을 잘 모르겠습니다.... 조금만 가이드를 주실 수 있을까요...?

2024-06-04 11:45 UTC, Hogu59 commented on app/src/androidTest/java/woowacourse/shopping/ShoppingActivityTest.kt
> +        )
https://github.com/woowacourse/android-shopping-order/pull/53#discussion_r1625852689

2024-06-04 11:46 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingItemsRepositoryImpl.kt
> +) : ShoppingItemsRepository {
이 내용은 이전 로컬 레포지토리의 구현체입니다! 불필요성이 더 느껴지면 삭제하도록 하겠습니다!

2024-06-04 11:53 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/domain/repository/RecentProductRepository.kt
> +    fun loadSecondLatest(): RecentProduct?
맨 마지막 조회한 상품과 마지막에서 두번재로 조회한 상품을 엮어서 `Result` 객체로 매핑하는걸 말씀하신걸까요..?
현재 loadLatest를 사용하는 곳과 loadSecondLatest를 사용하는 곳이 완전히 다른 상황입니다.
`loadLatest`는 RecommendFragment에서 사용되고,
`loadSecondLatest`는 DetailActivity에서 사용되고 있습니다.

만약 하나의 객체로 매핑한다면 각 위치에서 불필요한 정보를 하나씩 더 알게 되는 것 같아서 말씀해주신 매핑은 여기에서는 하지 않는 것이 조금 더 좋지 않을까 조심스럽게 생각이듭니다.

다만, 이후 한 액티비티에서 두가지 정보를 한번에 사용한다고 한다면 응집도를 높이기 위해서 하나의 객체로 매핑하는 것이 좋을 수 있겠다는 생각이 듭니다. 글을 적다보니, 아마도 가장 최근, 두번째 최근 상품에 대한 정보는 누가 봐도 서로 결합도가 높은 정보로 인식 될 가능성이 있어보이네요. 이건 메서드 네이밍에서 코드스멜이 나거나 로직이 명확히 보이도록 설계하지 못한 잘못인것 같습니다. 😅

2024-06-04 11:54 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +                    }
오 그렇게도 사용할 수 있겠군요... 다만 지금으로서는 uistate를 사용하는데에 덜 익숙하다보니 말씀해주신대로 구현하기가 아직 쉽지 않네요...
다음 단계 진행하면서 혹 가능하다면 구현해보도록 하겠습니다! 감사합니다! 😄 🙇

2024-06-04 12:15 UTC, Hogu59 commented
두루 안녕하세요,
반영이 조금 늦었네요...ㅎㅎ

코멘트 주신 내용에 대해서 답 달아두었고, 해당 내용에 대해서 반영해두었습니다.
중간중간 아직 모르는 내용(UITest에서 뷰모델이 repository를 생성자 인자로 받고 있는데, 따로 더미데이터를 넣어주는 방법, UiState Loading 등) 에 대해서는 아직 구현하지 못했습니다.

해당 내용은 좀 더 공부하면서 구현해보도록 하겠습니다!

리뷰 잘 부탁드립니다!

2024-06-04 13:10 UTC, Gyuil-Hwnag commented on app/build.gradle.kts
> +    implementation("com.squareup.retrofit2:retrofit:2.11.0")
타당한 의견 정말 좋습니다!!💯

2024-06-04 13:23 UTC, Gyuil-Hwnag commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true"
자세한 설명 정말 좋습니다~👍

2024-06-04 13:25 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +            .addConverterFactory(GsonConverterFactory.create())
말씀해주신대로 두가지 방법이 있습니다!
1. 특정 Kotlin 파일로 만든후 .gitignore로 제외를 시킨다.
2. local.properties에 만들어둔다.
단 1의 방법으로 할 경우 프로젝트의 구조가 변경된다면, 경로가 바뀌에 노출될 우려가 있으므로 주의를 하여야 할 것 같습니다~😀

2024-06-04 13:32 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/domain/repository/RecentProductRepository.kt
> +    fun loadSecondLatest(): RecentProduct?
타당한 의견 정말 좋습니다~👍
말씀을 해주신대로 단순 네이밍만 본다면, 왜 분리를 한거지..😯 라는 생각이 들 수도 있어서 다음 미션을 진행하면서 시간이 난다면, 유의미한 이름을 가지고 해보는 것도 좋을 것 같긴 합니다!💪

2024-06-04 13:33 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +                Log.d("crong", "setupState")
너무나 이해가 가는 테스트 해본 흔적이라서 괜찮습니다😆

2024-06-04 14:05 UTC, Gyuil-Hwnag approved these changes
악어 안녕하세요!
해당 미션 너무 고생 많으셨습니다!

해당 미션은 다음 미션 진행을 위하여 머지하도록 하겠습니다.
도움이 될만한 코멘트 달았으니 확인하여 다음 미션에서 반영해주셔도 좋을 것 같습니다.
남겨둔 코멘트와 미션을 진행하면서 사용 안하는 구현들에 대해서 코드 정리가 덜 된 부분들도 있는 것 같은데 다음 미션을 진행하면서 잘 정리해주시리라 믿겠습니다😀

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
레벨2 안드로이드 마지막 미션 화이팅입니다💪

2024-06-04 14:05 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_cart.xml
> +            app:layout_constraintBottom_toBottomOf="parent"
위에 남겨둔 visibility에 대한 코멘트에 추가적인 내용입니다!
`cartViewVisibility`, `~~ViewVisibility` 로 분리되어 있는 내용에 대해서 아래와 같이 통합을 해볼 수 있겠다는 생각이 듭니다~
~~~kotlin
    @BindingAdapter("viewGone")
    fun View.bindViewGone(isGone: Boolean?) {
        isGone?.let {
            val view = this
            view.isVisible = !it
        }
    }
~~~

2024-06-04 14:05 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/fragment_selection.xml
> +<!--            app:layout_constraintStart_toStartOf="parent">-->
해당 내용들도 다음 미션을 진행하면서, 정리해주시리라 믿겠습니다!😀

2024-06-04 14:05 UTC, merged