[쇼핑 주문] 에디 1, 2 단계 미션 제출합니다.
woowacourse/android-shopping-order pull request #54
Opened 2024-05-30 08:12 UTC by junjange

잘 부탁드립니다!! 🫡

2024-05-30 10:11 UTC, laco-dev commented
> https://github.com/junjange/android-shopping-order/compare/f565ec7..4f50ef1.

이렇게 남겨주신 경우, 구체적으로 어디서부터인지 확인이 어려울 수 있는데요.
이런 경우 

f565ec7 커밋부터 봐주시면 됩니다. 와 같이 남겨주시면 됩니다.

2024-05-30 10:16 UTC, laco-dev commented
> 서버 통신을 위한 JSON 직렬화 라이브러리를 선택하고 PR에 선택 이유를 남긴다.

내용을 남겨주세요

2024-05-30 11:30 UTC, laco-dev requested changes
마지막 미션인 만큼, 조금은 현실성 있는 질문을 드리려고 합니다.

아주 큰 규모의 PR을 올릴 때, 그리고 이 PR이 무엇인지 잘 모르는 상대에게 어떻게 해야 효과적으로 의도를 전달할 수 있을까요?
만약 에디라면, 6천줄의 PR을 리뷰한다고 가정했을 때 어떻게 시작하는게 좋을 것 같은지 고민을 해보면 좋겠습니다.

제 입장에서는 각 클래스나 화면이 어떤 역할을 하는지 전혀 모르기 때문에 의도를 파악하기 위해 여러가지 댓글을 남기게 되었습니다.

본문에, 이 PR에 대한 전반적인 설명과, 각 화면들이 하는 역할. 그리고 시연 영상을 같이 남겨주면 좋겠습니다.

아래는, PR에 대한 전반적인 수정 요구사항 입니다.
1. 도메인 데이터가 불필요한 정보를 가지지 않도록, 명확하게 도메인 개념의 타입으로 만들어주세요. 상품 데이터나 카트가 페이지 값을 알 이유는 없습니다.
2. 범위지정 함수나 리시버 등 여러가지 방법을 좋아하시는 것 같은데 가독성이 많이 떨어집니다. 객체 생활 체조 원칙에 따라 indent가 늘어나지 않도록 리팩토링 해주세요
3. 1번의 피드백이 잘 반영된다면 UI 상태에서 정말 필요한 데이터를 분리할 수 있어 보입니다.

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +                            }
카트에 아이디를 넣는다는 행위는 무엇을 의미하는 건지 잘 이해가 안되는데요.
카트에 상품을 담는 개념으로 생각이 되는데, 지금 구현을 어떻게 설계하신 것인지 알려주시겠어요?

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectBindingAdapters.kt
> +}
이 값을 결정하는 것은 UI가 해야할 일인가요? 뷰모델이 해야할 일인가요?

어디서든 currentPage, last, isLoading만 넣으면 텍스트가 숨겨질 것으로 생각을 해야 하는 것인지.
아래와 같은 테스트를 작성해서, UI 입장에서는 주는대로 그리기만 하면 되는 것일지.

어떻게 생각하시는지 알려주세요
```kotlin
private val _showPageIndicator = MutableLiveData<Boolean>
val showPageIndicator: LiveData<Boolean>

_showPageIndicator.value = { ... }

android:visibility="@{vm.showPageIndicator}"
```

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectFragment.kt
> +            (requireContext().applicationContext as ShoppingApplication).shoppingCartRepository,
일반적으로 Application을 글로벌로 관리할 때는 캐스팅 하는 대신 정적 함수를 사용하고는 합니다.
`ShoppingApplication.getInstance()`

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectFragment.kt
> +        }
*반영하지 않아도 됩니다.

이전 단계에서 프래그먼트가 사용되어서 지금 구조가 된 것으로 보이는데요.
프래그먼트는, 액티비티와의 의존성을 가지는 것은 지양해야 합니다.
화면 이동을 결정하고 관리하는 것은 상위 액티비티가 하고 있습니다.
하지만 지금 구현에서는 ParentFragmentManager를 접근해, 화면을 임의로 이동 시키고 있는데요.

그렇기에, 네비게이션 구조를 액티비티가 할 수 있도록 역할을 잘 나눌 수 있어야 합니다.
```kotlin
(activity as? CartSelectNavigateAction)?.navigateOrderRecommentation()
...
```

즉 NavigateAction 인터페이스를 액티비티가 구현해야 한다는 의미입니다.

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectUiState.kt
> +) {
주문한 카트 목록의 키값인 Int가 무엇을 의미할까요? 또한 외부에서 마음껏 HashMap의 데이터를 조작할 수 있겠네요.

캐시가 필요하다면, 이는 UI 상태가 아닌 뷰모델이 관리해야 하지 않을까요?

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectViewModel.kt
> +    ) {
단순히 수량을 증가시키는 로직인데, 함수가 너무 복잡합니다.
상태를 변경시키기 위한 알고리즘적인 해석이 어렵게 되지는 않았을까요?

뭔가 이 화면의 데이터를 그리기 위해 불필요한 정보를 알고 있는 것은 아닐까요?

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectViewModel.kt
> +    }
리시버 함수를 사용하는 좋은 예시는 아닙니다.
this는 ViewModel이 될 수도 있고 Cart가 될 수도 있습니다.

범위 지정 함수와 같이 좋아하시는 것 같은데, 현업에서는 잘못 사용하면 가독성을 심각하게 떨어트리는 요소가 될 수 있습니다.

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/orderrecommend/OrderRecommendUiState.kt
> +    val orderCarts: MutableMap<Int, Cart> = hashMapOf(),
마찬가지로 추천 화면에서 이 필드가 어떤 목적으로 사용되는지 잘 연결이 안됩니다.

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/orderrecommend/OrderRecommendViewModel.kt
> +            productHistoryRepository.getProductHistoriesByCategory(10)
`findViewById(id)` 와 같이 사용하는 것 처럼,  ByCategory() 와 같이 사용하고 있는데, 실제로는 카테고리를 넘기지 않고 있어요.

인터페이스 메소드 이름을 다시 고민 해 봐야 하지 않을까요?

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/orderrecommend/adapter/RecommendAdapter.kt
> +    open class RecommendViewHolder(
open이 붙은 이유가 있나요?

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/res/layout/activity_product_list.xml
> +                android:visibility="@{vm.loading ? View.VISIBLE : View.GONE}" />
이 역할을 하는 바인딩 어댑터를 만들고 사용할 수 있습니다.

```
app:visibility="@{boolean}"
```

2024-05-30 11:30 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/remote/api/NetworkModule.kt
> +import woowacourse.shopping.app.ShoppingApplication.Companion.BASE_URL
Network 모듈이 BASE_URL을 역으로 참조해도 되는 것일까요?
AuthProvider도 그럼 직접 접근해도 되는 것이지 않았을까요?

2024-05-30 11:33 UTC, laco-dev commented
아~ 테스트 코드도 하나도 없군요 😱

2024-05-30 11:34 UTC, laco-dev commented
변경된 구현에대한 테스트도 추가가 필요해보이네요 😓

2024-05-31 05:20 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/model/remote/SortDto.kt
> +)
활용되고 있지 않습니다. 아래 코멘트와 같이 서버에서 내려주는 API 스펙을 그대로 만들고 있습니다! 사용되지 않는 필드는 제거하도록 하겠습니다.

2024-05-31 06:22 UTC, junjange commented on app/src/main/java/woowacourse/shopping/app/ShoppingApplication.kt
> +
네네! 개선하도록 하겠습니다!!

2024-05-31 06:55 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/model/remote/ProductsDto.kt
> +)
네네! 개선하도록 하겠습니다!

2024-05-31 07:09 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +
early return과 함수 분리를 잘 활용하여 개선하도록 하겠습니다!!

2024-05-31 08:28 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/repsoitory/ProductRepositoryImpl.kt
> +                .getOrThrow().totalElements
맞습니다!! 개선하도록 하겠습니다!!

2024-05-31 14:13 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/repsoitory/ShoppingCartRepositoryImpl.kt
> +    ): Result<Int> =
이해하지 못할 것 같습니다! 개선하도록 하겠습니다!

2024-05-31 14:41 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +                            }
전체적으로 리팩터링 하겠습니다!

2024-05-31 14:42 UTC, junjange commented on app/src/main/java/woowacourse/shopping/remote/api/NetworkModule.kt
> +import woowacourse.shopping.app.ShoppingApplication.Companion.BASE_URL
참조하면 안 될 것 같습니다!! 파라미터로 BASE_URL을 받을 수 있도록 개선하겠습니다!

2024-05-31 15:10 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +                        updateCart(cart)
처음 보는 개발자가 이해하기는 어려울 것 같습니다!

위와 같이 구현한 이유는 API 스펙과 관련과 상품 데이터 형태에 대한 이야기를 해야할 것 같습니다.

```
- 장바구니에 상품을 담기 위해서는 `product id`를 `request`로 넘겨야 한다.
- 장바구니에 담긴 상품의 수량을 변경하기 위해서는 `cart id`를 `request`로 넘겨야 한다.
```

위와 같이 API 스펙이 주어졌기 때문에 `cartId`, `product`, `quanutity` 를 포함하고 있는 `Cart`를 모든 상품에 대한 데이터로 지정했습니다. 결국, 장바구니가 없는 상품은 cartId, quantity를 디폴트 파라미터로 초기화했고 그것이 아니라면 해당 `cartId`와 `quantity`로 초기화 했습니다. 

따라서 `cartId`가 `DEFAULT_CART_ID`라면 장바구니에 없는 상품으로 장바구니에 추가하고, `DEFAULT_CART_ID` 아니라면 이미 장바구니에 있는 상품으로 수량을 변경하는 것으로 구현했습니다.

2024-05-31 15:13 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +            Thread.sleep(1000) // TODO 스켈레톤 UI를 보여주기 위한 sleep..zzz
미션을 구현하다보니 로딩을 하면 스켈레톤 UI가 보여야한다는 것으로 너무 당연시 생각했던 것 같습니다.
개선하도록 하겠습니다!

2024-05-31 15:56 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectBindingAdapters.kt
> +}
UI는 그저 보이거나 이벤트(사용자 인터렉션)를 발생시키는 것만 하는 것으로 상태를 통해 처리하는 로직은 뷰모델에 있어야할 것 같습니다!

2024-05-31 17:09 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +                            }
https://github.com/woowacourse/android-shopping-order/pull/54#discussion_r1622571409
위에 코멘트에 관련한 내용을 남겼지만 추가적으로 설계에 대해 코멘트 남기도록 하겠습니다.

코멘트에서도 언급했듯이 상품을 추가할 때는 `productId`를 request로 필요했고, 상품의 수량을 변경할 때는 `cartId`가 request로 필요했습니다. 결국, 상품을 추가하고 수량을 바꾸는 로직을 효율적으로 처리하기 위해서는 상품 데이터 하나의 productId와 cartId가 포함되어 있으면 좋겠다는 생각을 했습니다. 상품이기에 Product라는 객체의 cartId와 quantity 프로퍼티를 포함하는 새로운 객체를 만들까도 고민했지만, 그 객체는 Cart와 동일한 객체이기에 Cart라는 객체를 상품 데이터 모델로 통일하여 사용하기로 했었습니다.

따라서 위에 코드를 보면 상품을 장바구니에 성공적으로 넣었기 때문에 해당 상품을 장바구니에 넣은 상품의 cartId로 바꿔주는 것을 알 수 있습니다.

2024-05-31 17:22 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/orderrecommend/adapter/RecommendAdapter.kt
> +    open class RecommendViewHolder(
헉 잘못작성했습니다! 지우도록 하겠습니다!

2024-05-31 17:22 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectFragment.kt
> +            (requireContext().applicationContext as ShoppingApplication).shoppingCartRepository,
개선했습니다!

2024-05-31 17:25 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectViewModel.kt
> +    ) {
좀 더 고민해보도록 하겠습니다!

2024-05-31 17:27 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectViewModel.kt
> +    }
가독성 좋은 코드를 작성할 수 있도록 개선해보도록 하겠습니다!!

2024-05-31 17:43 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/orderrecommend/OrderRecommendViewModel.kt
> +            productHistoryRepository.getProductHistoriesByCategory(10)
처음에 카테고리를 클라이언트에게 받아와 추천 상품을 제공하려고 했지만, 최근 본 상품의 카테고리는 DB에 저장되어 있기 때문에 클라이언트가 컨트롤하는 것은 아니라고 판단하여 카테고리를 넘기지 않게 되었습니다. 이런 과정을 통해 코드를 수정하다보니 메서드명을 수정하지 못했습니다! 수정하도록 하겠습니다!

2024-06-01 01:49 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/repsoitory/ProductHistoryRepositoryImpl.kt
> +            )
https://github.com/woowacourse/android-shopping-order/pull/54#discussion_r1622761031
이부분은 위 코멘트와 연관이 되어있습니다.

```
- 최근 본 상품은 `Product`이지만, 장바구니에 담겨있는 상품은 `Cart`이다. 
- 최근 본 상품 중에 특정 카테고리인 상품을 추천 상품으로 보여줘야 한다.
- 추천 상품 중에서 이미 장바구니에 있는 상품이면 추천 상품으로 보여지면 안된다.
- 추천된 상품은 상품 주문 화면에서 바로 추가하여 같이 주문할 수 있다.
```

위 요구사항을 수행하기 위해 `Repository`에서 최근 본 상품과 장바구니에 상품 데이터를 불러와 추천 상품으로 가공했고, 상품을 추가하거나 수량을 변경해야하는 경우가 발생할 수 있으므로 `Cart` 타입을 반환하게끔 구현했습니다.

이러한 로직이 Repository에 있는 게 어색할까요?! 아니면 아래에서 언급해주신 네이밍이 문제였을까요?! 아니면 도메인 설계가 잘못되어 이러한 문제가 발생한걸까요?!

2024-06-01 06:23 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectUiState.kt
> +) {
주문한 카트 목록의 키값은 `cartId`를 의미합니다!

리팩터링 과정에서 데이터 구조를 `List`로 수정했고, `orderCartList`에 있는 데이터로 총 구매 가격, 개수 등 UI를 나타내고 있기 때문에 `UiState`에 계속 두었습니다!

2024-06-01 06:28 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/orderrecommend/OrderRecommendUiState.kt
> +    val orderCarts: MutableMap<Int, Cart> = hashMapOf(),
상품 추천 화면에서 추천된 상품도 함께 구매할 수 있기 때문에 `orderCarts`라는 프로퍼티로 추천된 상품도 함께 담을 수 있게 구현한 것입니다!

2024-06-01 18:18 UTC, junjange commented
# 구현 사항
- 전반적으로 코멘트와 관련된 로직 리팩터링
- 코드 가독성을 높이기 위한 리팩터링
- 단위 테스트 코드 추가 구현

# 전달 사항
### 질문
- UI와 직접적인 데이터 및 로직이 아니라면 Repository에서 데이터 가공 및 비즈니스 로직을 처리해도 되는지 궁금합니다!
- Repository를 통해 데이터를 받아올 때, 해당 메서드의 파라미터를 만들어 파라미터 변수와 조합하여 데이터를 받아오는 로직을 구현해도 괜찮은 지 궁금합니다!

2024-06-02 13:43 UTC, laco-dev requested changes
피드백 반영 고생하셨습니다.

우테코의 시작부터 코드의 의도를 전달하는 가장 쉬운 방법은, 분리라는 것을 배웠을거에요.
그렇기에 함수를 분리하거나 클래스를 분리하는 등 조금더 작은 관심사로 나누는 연습을 해왔구요.

만약 의도를 충분히 전달되기 어렵다는 생각이 든다면 분리를 할 때다 라는 신호가 됩니다.
관련해서 반복되는 코드나 의도가 전달되기 어려운 코드를 분리해보는 것도 좋습니다.

남겨주신 질문은 댓글에 같이 두겠습니다.
다음 3, 4 단계 미션을 위해서 간단한 수정사항들만 추가로 작성했습니다.

2024-06-02 13:43 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +                updateCart(cart)
> 이것을 다시 어떻게 설계해야 할 지는 더 고민해봐야 할 것 같습니다!

코드의 의도를 전달하는데 가장 효과적이고 쉬운 방법은, 함수를 나누는 것입니다.
```kotlin
if (shoulInsertCart(cart)) {
  insertCart()
} else {
  updateCart(...)
}

// 더이상 이 함수가 왜 필요한지, 무슨 역할을 하는지 알릴 필요가 없어짐. 함수에 의미가 담겨 있으니까
private fun shouldInsertCart() { ... }
```

2024-06-02 13:43 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +            _uiState.value = state.copy(cart = cart.copy(quantity = cart.quantity + 1))
그럼에도 let을 정말 좋아하시기는 하군요..
사실 개인 취향차이라 여기까지만 언급을 하겠습니다.

저라면 한번더 early return을 사용했을 것 같아요. (이정도까지는 취향의 영역입니다)
```kotlin
val state = uiState.value ?: return
val cart = state.cart ?: return
...
```

2024-06-02 13:43 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/base/BaseViewModel.kt
> +        _loading.postValue(null)
로딩 상태를 Base에서 관리하는 것은, 편리할 수 있지만 매우 위험한 문제를 가지고 있습니다.

가령, 로딩이 필요한 비즈니스 로직이 한번에 5개의 요청이 들어왔다고 가정 해봅시다.
그렇다면 각각 함수에서는 showLoading()을 5번까지 요청을 합니다.
이어서 하나의 함수라도 요청이 끝난다면 hideLoading()을 부르게 됩니다.

그러면 아직 4개의 함수가 끝나지 않았는데 UI가 보이는 문제로 이어집니다.
여러가지 솔루션이 있지만, 지금 생각하기에는 난이도가 다소 높을 지 모릅니다.

수정을 요구하는 바는 아니지만, 고민은 해보셨으면 좋겠습니다

2024-06-02 13:43 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectViewModel.kt
> +        }
비동기를, 뷰모델에서 처리할 수도 있고 레포지터리에서도 처리할 수 있게 되는데요.
이에 대한 장단점은 명확히 있지만, 3, 4단계 비동기 프로그래밍을 하면서 고민을 하게 될 예정이라 우선은 남겨만 둡니다.

2024-06-02 13:43 UTC, laco-dev commented
> Repository를 통해 데이터를 받아올 때, 해당 메서드의 파라미터를 만들어 파라미터 변수와 조합하여 데이터를 받아오는 로직을 구현해도 괜찮은 지 궁금합니다! (이때 파라미터에 들어가는 모델은 도메인 모델이 될 것 같습니다!)

뭔가 당연한 말을 작성해주신 것 같은데, 정확히 어떤 문제인지 이해가 잘 안되네요

2024-06-02 13:45 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/repsoitory/ProductHistoryRepositoryImpl.kt
> +            )
정확히 네이밍이 문제였습니다.

2024-06-02 13:46 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +                            }
성공적으로 넣었다..?

List에 아이템이 들어가는 것으로 기대할 것 같은데, 이미 있는 아이템에 아이디를 다시 셋업할 필요가 있는 것이었을까요?

2024-06-02 13:47 UTC, laco-dev commented on app/src/main/res/layout/activity_product_list.xml
> +                android:visibility="@{vm.loading ? View.VISIBLE : View.GONE}" />
이전처럼 바인딩 어댑터에 로직이 포함되는 것만 아니라면 어떤 방법이던지, 일관성 있게 가는게 중요합니다.
다른 팀원들과 협의 후 결정!

2024-06-03 08:55 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +                            }
상품 목록의 아이템 타입을 `Cart`로 했었기 때문에, 장바구니에 상품을 넣은 후에 디폴트값인 `CartId`를 실제 `CartId`로 셋업하는 로직이 생겼습니다.

그러나 리뷰를 받고 곰곰이 생각해보니 상품을 등록한 후에 이미 있는 아이템의 아이디를 초기화하는 것은 어색한 것 같다는 생각을 했습니다. 따라서 `productId`를 `key`로 하고 `CartId`를 `value`로 하는 `map`을 만들어 이미 장바구니에 있는 아이템은 `map`에서 `CartId`를 꺼내서 수량을 조절하는 방식으로 개선했습니다.

2024-06-03 09:01 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +            _uiState.value = state.copy(cart = cart.copy(quantity = cart.quantity + 1))
헉 개선한다고 했는데 다 하지 못했네요ㅠㅠ 다시 개선하겠습니다!

2024-06-03 09:05 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +            updateCartProduct(cart.id, updatedQuantity)
아니요.. 개선을 하면서도 더 나아졌다는 생각은 하지 못했습니다..

위 코멘트들을 수정하면서 상품 목록의 아이템을 Product로 리팩터링했습니다. 
따라서 위 로직은 사라졌고 

```
private fun updateCart(
        productId: Long,
        updatedQuantity: Int,
    ) {
        val cartItemId = shoppingCart[ProductItemId(productId)]
        if (cartItemId == null) {
            insertCartProduct(productId, updatedQuantity)
            return
        }

        if (updatedQuantity <= 0) {
            deleteCartProduct(productId, cartItemId.id)
        } else {
            updateCartProduct(cartItemId.id, updatedQuantity)
        }
    }

```

좀 더 나은? 가독성 좋게 리팩터링 되었습니다.

2024-06-03 10:28 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectViewModel.kt
> +                        state = state.copy(orderCarts = state.orderCarts + updateProduct.cart)
productId에 따라서 Cart를 캐싱하는 로직으로 개선하면서 위 코드에 비해 엄청나게?! 가독성이 올라갔습니다!

2024-06-03 11:48 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectViewModel.kt
> +            updateCartProduct(cart.id, updatedQuantity)
아닙니다!! 제가 알고있는 것이 맞는지 확인하고 싶어서 여쭤본 것입니다!!

2024-06-04 01:17 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectActionHandler.kt
> +    fun checkCartProduct(cartProduct: CartProduct)
`OFF`도 `checkCartProduct`를 통해 실행됩니다.

`updateCheckState`로 수정하도록 하겠습니다!

2024-06-04 01:18 UTC, junjange commented on app/src/main/java/woowacourse/shopping/presentation/base/BaseViewModel.kt
> +        _loading.postValue(null)
좀 더 고민해보고 생각을 전달드리도록 하겠습니다!!
조언 감사합니다!!

2024-06-04 01:29 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/model/remote/CartsDto.kt
> +    val pageableDto: PageableDto,
개선하도록 하겠습니다!

2024-06-04 01:29 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/repsoitory/ProductHistoryRepositoryImpl.kt
> +                        size = ProductRepositoryImpl.FIRST_SIZE,
네네! 개선하도록 하겠습니다!

2024-06-04 02:37 UTC, junjange commented on app/src/main/java/woowacourse/shopping/app/ShoppingApplication.kt
> +                PreferenceManager.getDefaultSharedPreferences(applicationContext),
네네 개선하도록 하겠습니다!!

2024-06-04 04:09 UTC, junjange commented on app/src/main/java/woowacourse/shopping/local/provider/AuthProviderImpl.kt
> +        }
예상하신대로 편의를 위해 `AuthProviderImpl`를 생성할 때 `apply`로 호출하여 계정 정보를 저장하게끔 했습니다...

아이디와 비밀번호를 저장하기 위해서는 `local.properties`에 숨겨야 할 것 같습니다.
계정 정보에 대한 핵심 주체 관리 역할은 `AuthProvider`인 것 같습니다!!............

2024-06-04 05:05 UTC, junjange commented
> 뭔가 당연한 말을 작성해주신 것 같은데, 정확히 어떤 문제인지 이해가 잘 안되네요

문제보다는 비즈니스 로직을 `ViewModel`에서 `Repsitory`로 빼도 되는지 궁금해서 질문드린 것입니다!!😊
예를들어 아래와 같은 코드가 `RepositoryImpl`에 있다고 가정해보겠습니다!
```kotlin
override fun findCartByProductId(id: Long, carts : Carts): Result<Cart> {
        val totalElements = shoppingCartDataSource.getCartProductTotalElements().getOrThrow()

        return productDataSource.findProductById(id).mapCatching { productDto ->
            val cart = carts.firstOrNull { it.product.id == productDto.id }
            cart ?: Cart(
                product = productDto.toDomain(),
                quantity = INIT_QUANTITY,
            )
        }
    }
```


파라미터로 받은 `carts`와 `productDataSource.findProductById(id)`를 통해 얻은 `productDto`를 조합하여 ViewModel에서 원하는 데이터로 반환해도 되는지 궁금합니다!!

2024-06-04 13:44 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/local/provider/AuthProviderImpl.kt
> +        }
서버 주소와.. 계정 정보는 차이가..?

2024-06-04 13:45 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/shoppingcart/cartselect/CartSelectActionHandler.kt
> +    fun checkCartProduct(cartProduct: CartProduct)
일반적으로는 toggleXXX()를 사용하면 됩니다.

2024-06-04 13:47 UTC, laco-dev commented
> 파라미터로 받은 carts와 productDataSource.findProductById(id)를 통해 얻은 productDto를 조합하여 ViewModel에서 원하는 데이터로 반환해도 되는지 궁금합니다!!

뷰모델에서 하는게 적절한 경우가 있고.
명확한 비즈니스 로직 데이터 로직으로 봐서 위에서 할 수도 있습니다.

이건 여러가지 경험을 해보셔야 알 수 있기 때문에 딱히 정답이라고 드리기는 어렵겠네요

2024-06-04 13:55 UTC, laco-dev approved these changes
좋습니다.

2번 까지 피드백 반영하시면서, 많은 부분 개선되었네요.
마지막 미션의 마지막 단계인 만큼, 집중도를 높이기 위해 따로 피드백은 남기지 않았습니다.

비동기 프로그래밍에 대해 학습하신 것을 토대로, 어떤 레이어에서 비동기를 처리할지 어떻게 할지 잘 생각 해보세요!

2024-06-04 13:56 UTC, merged

2024-06-12 07:48 UTC, junjange commented on app/src/main/java/woowacourse/shopping/local/provider/AuthProviderImpl.kt
> +        }
서버 주소는 고정적이지만 계정 정보는 유동적일 것 같습니다.

그러나 현재 프로젝트에서는 계정 정보가 고정적일 것 같습니다!