[쇼핑 주문] 팡태 1, 2 단계 미션 제출합니다
woowacourse/android-shopping-order pull request #60
Opened 2024-05-30 08:46 UTC by Hevton

안녕하세요 말리빈! 이번 미션 잘 부탁합니다..!!
[6cd9d98](https://github.com/woowacourse/android-shopping-order/pull/58/commits/6cd9d98552c81402f03feab69d5010ce3405c782) 부터 봐주시면 됩니다!

```
계정 정보
user: hevton
password: password
```
이번 미션을 진행하면서 궁금했던 점은 다음과 같으며, 여러가지 상황에 대해 오류가 없게 기능에 대한 사항은 구현했다고 생각하고 있습니다.
하지만 androidTest는 깨지지 않는데, 기존 viewModel 테스트는 이행하지 못했고.. 리팩터링이 잘 되지 못한 상황입니다.

서버 통신을 위한 JSON 직렬화 라이브러리는 kotlinx-serialization 을 사용했습니다.
gson은 nullable 을 기본적으로 받지 않기에, 어노테이션으로 해주지 않으면 null 값이 왔을 때 터지는 것으로 알고 있습니다. 
서버에서 혹여나 null 데이터가 왔을 때 유연하게 대처할 수 있고, 코틀린 프로젝트이기에 serialization을 사용했습니다.

궁금한 점이 있습니다!

case 1. 장바구니에서 삭제를 진행했습니다.
A. 서버 API를 호출하여 성공적으로 삭제를 진행했을 때, 장바구니 로드 API를 다시 호출하여 가져올지
B. 아니면 성공한 결과를 토대로, 현재 관리하고 있을 MutableLiveData<List<Cart>> 에서 해당 아이디를 찾아서 직접 지워줘야 할지 고민을 했는데, 저는 후자를 진행했습니다.
코드적으로 깔끔한건 전자이고, 로직적으로 괜찮은건 후자라고 생각했는데 보통은 어떻게 하는지 궁금합니다.

case 2. 상품 리스트에서 디테일로 이동하여 수량을 변경한 뒤에 장바구니에 담았습니다. 
그러면 다시 상품 리스트로 왔을 때, 변경된 수량을 상품 리스트에서도 업데이트해주기 위해서 
A. 디테일 화면에서 수정된 것을 intent로 담아서 상품 리스트에서 받아서 반영하는 방법과
B. 다시 onResume에서 상품 리스트를 다시 API 요청하는 방법 중
보통은 어떻게 하는지 궁금합니다.

저는 대부분 API 요청을 최소화해보려는 느낌으로 진행했습니다.

https://github.com/woowacourse/android-shopping-order/assets/86276828/04897c98-a241-4936-b2be-673bcc27b779

2024-05-31 04:49 UTC, malibinYun requested changes
안녕하세요~ 저도 잘 부탁드려요!
여러 고민해볼 곳에 코멘트 남겨두었으니 충분히 고민하는 시간 가져보세요!
못했던 부분들 더 수행해보시고, 피드백 반영 후 다시 리뷰 요청 부탁드려요!

2024-05-31 04:49 UTC, malibinYun commented on app/build.gradle.kts
> +    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
> 서버 통신을 위한 JSON 직렬화 라이브러리는 kotlinx-serialization 을 사용했습니다.
gson은 nullable 을 기본적으로 받지 않기에, 어노테이션으로 해주지 않으면 null 값이 왔을 때 터지는 것으로 알고 있습니다.
서버에서 혹여나 null 데이터가 왔을 때 유연하게 대처할 수 있고, 코틀린 프로젝트이기에 serialization을 사용했습니다.

non-null 필드로 정의한 모델에서 서버에서 데이터를 주지 않았을 때 터지는 건 오히려 kotlinx-serialization 인데요!
다른 이유가 더 필요해보이네요!

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/ProductPagingSource.kt
> +
페이지에 대한 상태는 정말 데이터를 저장하는 곳의 역할일까요?

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/RetrofitDataSource.kt
> +
Call 객체에 enqueue() 를 호출하지 않고, execute()를 호출한 이유가 궁금하네요!
둘은 어떻게 다를까요?

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/RetrofitDataSource.kt
> +
그리고 이 코드 구조는 정말 "비동기 요청"이었는지 다시 되새겨보세요!

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/dto/request/CartItemRequest.kt
> +data class CartItemRequest(
이 객체는 뭔가 실행하면 직접 요청을 보낼 것만 같은 이름이네요!
요청을 보내기 위한 값을 담는 객체라는 의미를 녹여내보는 건 어떨까요?

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/domain/Repository.kt
> +    fun getProductsByPaging(): Result<List<CartProduct>?>
nullable List 를 반환하는 이유가 궁금하네요! emptyList()를 반환하는 것과는 어떻게 달랐나요?

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                            cartAdapter.submitList(it.data)
xml에 데이터바인딩 기능을 더 적극적으로 활용해주세요!
데이터바인딩을 활용하지 않으면 MVVM이라 부르기에는 큰 요소가 빠지게되지요.

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/presentation/ui/curation/CurationViewModel.kt
> +    private val repository: Repository,
Repository 는 어떤 것을 저장하는지 알기에는 어려워보이네요.
더 구체적인 이름으로 지어보는 건 어떨까요?

2024-05-31 04:49 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailViewModel.kt
> +    fun setCartProduct(cartProduct: CartProduct?) {
입력이 null일때 메서드가 아무 일도 하지 않는다면, null은 받지 못하도록 만드는 건 어떨까요?

2024-05-31 04:52 UTC, malibinYun commented
> case 1. 장바구니에서 삭제를 진행했습니다.
A. 서버 API를 호출하여 성공적으로 삭제를 진행했을 때, 장바구니 로드 API를 다시 호출하여 가져올지
B. 아니면 성공한 결과를 토대로, 현재 관리하고 있을 MutableLiveData<List> 에서 해당 아이디를 찾아서 직접 지워줘야 할지 고민을 했는데, 저는 후자를 진행했습니다.
코드적으로 깔끔한건 전자이고, 로직적으로 괜찮은건 후자라고 생각했는데 보통은 어떻게 하는지 궁금합니다.


> case 2. 상품 리스트에서 디테일로 이동하여 수량을 변경한 뒤에 장바구니에 담았습니다.
그러면 다시 상품 리스트로 왔을 때, 변경된 수량을 상품 리스트에서도 업데이트해주기 위해서
A. 디테일 화면에서 수정된 것을 intent로 담아서 상품 리스트에서 받아서 반영하는 방법과
B. 다시 onResume에서 상품 리스트를 다시 API 요청하는 방법 중
보통은 어떻게 하는지 궁금합니다.

이 두 질문 모두 "보통" 하는 방법은 없다고 밖에는 답변 드리기가 어렵네요.
모두 목적에 의해 코드를 작성해요.
서버에서 얼마든지 api를 호출해도 상관 없고 비용적인 문제도 없으니 마음껏 불러라고 하는 환경이라면, 100번이고 1000번이고 호출해도 되겠지요.
그러나 서버에서 최대한 api를 필요에 의해 호출해달라 했다면, 최소한으로 호출해야겠지요.
그러나 최대한 최신의 정보를 보여주어야한다면, 필요에 의해 여러번 호출해야겠지요.
많은 경우의 수를 고려해보고, 어떤 목적으로 코드를 구성했는지 스스로의 근거를 잘 쌓아보세요!

2024-06-03 05:21 UTC, Hevton commented on app/build.gradle.kts
> +    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
말리빈 안녕하세요! 제가 잘못 알고 있는 부분이 있을까요? 

Gson에서는 기본적으로 Not Null 한 변수에 null 값이 들어갈 경우 런타임 오류가 발생할 수 있습니다.
하지만 코틀린의 경우에는 널 세이프티이기에 널러블을 기본적으로 지정해줄 수 있고, 기본값을 지정해 줄 수도 있기 때문에 서버에서 값을 누락시켜 보낼 경우에 예외가 발생하지 않을 수 있습니다.

2024-06-03 05:21 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/ProductPagingSource.kt
> +
페이징을 관리하는 페이징소스에서 오프셋/페이지 값을 알고 있어야 한다고 생각했는데, 그게 아니라면 어디서 알고 있어야 할지 잘 모르곘습니다..

2024-06-03 05:28 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/RetrofitDataSource.kt
> +
enqueue를 호출하면 AsyncTask처럼 작업스레드에서 작업을 한 뒤에, 작업이 끝난 뒤 메인스레드에서 마무리 작업을 할 수 있다고 알고 있습니다! 그 대신 스레드가 block되는 execute를 사용했는데요, 이는 데이터를 요청하는 곳과 결과를 받는 곳을 모두 ViewModel로 두기 위해서였습니다! 단, thread로 작업 스레드를 새로 열고 있지만 execute가 진행되는 동안 작업스레드는 block될 수 있겠습니다.
이 코드 흐름을 코루틴으로 옮겨가면 개선될 수 있겠다는 생각이 들었습니다!

2024-06-03 05:36 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/dto/request/CartItemRequest.kt
> +data class CartItemRequest(
DTO에서 
요청에 관한 것은 ~Request
응답에 관한 것은 ~Response
로 네이밍했는데요! 어떤 말씀이신지 잘 모르겠습니다..! ㅜㅜ

RequestDto 로 네이밍 하는 방향을 조언해주신 것일까요?

2024-06-03 05:37 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/domain/Repository.kt
> +    fun getProductsByPaging(): Result<List<CartProduct>?>
아 이부분은 emptyList로 하는게 가독성이 더 좋을 것 같다고 바로 느꼈습니다..!!
nullable보다 emptyList로 리턴했을 때 반영하는 면에서도 데이터 로직을 통일화 시킬 수 있겠습니다

2024-06-03 05:40 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                            cartAdapter.submitList(it.data)
말리빈과도 한번 이야기 나눠보고 싶은 부분인데요!

ViewBinding + UiState + ViewModel 방식은 MVVM이라고 보기 어려운가요?
저는 databinding이 에러 처리가 어렵다고 느꼈습니다.

그리고 UiState처럼 다양한 State를 다룰 때에는 bindingAdapter를 정의해주어야하는데, 그 과정이
결국 Activity에서의 바인딩 작업을 따로 뺀 것 뿐이라는 느낌을 받았습니다. 또한 매번 bindingAdapter에서 State를 casting해줘야 한다는 점에서, 확장성과 가독성에서 Activity에서 상태에 따라 처리해주는게 더 좋다는 느낌을 받았습니다.

2024-06-03 05:42 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/curation/CurationViewModel.kt
> +    private val repository: Repository,
말리빈! 제 프로젝트에서 현재 하나의 Repository 구현체만 모든 곳에서 사용하고 있어서 네이밍에 어려움이 있었는데요..!!
이 부분 더 고민해보겠습니다..

2024-06-04 04:22 UTC, malibinYun commented on app/build.gradle.kts
> +    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
gson의 non-null 필드에 값이 오지 않았을 경우, 언제 앱이 비정상 종료되는지,
kotlinx-serialization의 non-null 필드에 값이 오지 않을 경우 언제 앱이 비정상 종료되는지 비교해보세요!

2024-06-04 04:24 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/ProductPagingSource.kt
> +
똑같은 기능의 페이징을 제공하는 화면이 여러개이지만, 각 화면별로 보여주는 페이지 당 개수가 다르다면, 오프셋과 페이지의 값은 정말 "데이터를 저장" 하는 곳의 역할일까요?

2024-06-04 05:03 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/RetrofitDataSource.kt
> +
코루틴으로 손쉽게 옮기기 위해 execute를 사용하는 것은 받아들이기 어렵네요.
앞으로 변경될 라이브러리를 위해 지금 스레드를 막아버리고 성능에 대해 생각하지 않는다는 것은 엔지니어로써 납득하기 어려워요.
코루틴을 사용하면 비동기 프로그래밍을 해야할 것을 동기적으로 코드를 짤 수 있는 것은 맞으나, 비동기 프로그래밍을 할 줄 몰라도 된다는 의미로 받아들인다면 굉장히 곤란해요.

코루틴을 사용하지 않는 프로젝트나, 외부 라이브러리의 도움을 받아서는 안되는 프로젝트를 진행할 때,
나는 코루틴 밖에 쓸 줄 모르니 개발 못해! 라고 하면 회사는 그것을 존중해줄까요? 오히려 그것을 개발할 수 있는 다른 인력으로 교체를 하는 것이 회사 입장에서는 효율적인 방법이겠지요.

이 미션에서 코루틴이 나오게 된 계기는 감히 추측하기로, 비동기 프로그래밍의 불편한 점을 먼저 1, 2단계에서 학습하고 체험한뒤, 3, 4단계에서 코루틴으로 마이그레이션 함으로써 코드가 어떻게 바뀌고, 얼마나 편해지는지 체험 하는 것이 목표란 생각이 드네요 :)
그러면서 비동기 프로그래밍에 대한 지식과 코루틴을 활용하는 방법 두 가지를 다루는 무기를 크루들에게 챙겨주면서요.

자신에게 도움이 되는 무기를 꼭 자기 손으로 쥐고 다룰 수 있게 되었으면 좋겠어요 :)

2024-06-04 05:06 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/dto/request/CartItemRequest.kt
> +data class CartItemRequest(
RestAPI에서 이런식으로 데이터를 넘길 때 어떤 이름을 쓰는지 알아보시면 좋겠네요!

아래 두 이름을 한글로 해석했을 때,
- CartItemRequest - 카트항목요청
- CartItemResponse - 카트항목응답

저에게는 "카트항목요청" 은 정말 요청을 보내는 행위라고 생각이 들지, "요청을 보낼때 필요한 값"이란 생각이 들지 않아서요 :)

2024-06-04 05:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                            cartAdapter.submitList(it.data)
네! Binder 레이어를 활용하지 않는 것은 [MVVM 아키텍처](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel)가 아닙니다.
재미있게도 안드로이드 공식 문서에는 "MVVM" 이라는 단어가 전혀 등장하지 않는데요, 이유가 무엇일지 스스로 고민해보는 것도 좋은 학습 방법이란 생각이 드네요 :)
하지만 머리가 뿌셔질 수도 있으니 나중에 천천히 생각해보셔도 좋겠어요.

에러 처리가 어려운 것은 더 구체적으로 어떤 것이 어려웠나요?
View에서 로직에 대한 에러처리를 하는 것이 적절했는지 고민해보셔도 좋겠어요 :)

> 그리고 UiState처럼 다양한 State를 다룰 때에는 bindingAdapter를 정의해주어야하는데, 그 과정이
결국 Activity에서의 바인딩 작업을 따로 뺀 것 뿐이라는 느낌을 받았습니다.

저도 공감이 가는 점이에요.
이렇게 스스로 고민 하시고 스스로 결론을 내리는 자세가 너무 좋네요 👍
여담이지만, 이런 고민들로 저는 결국 아키텍처를 엄격히 지키는 것은 실무와 가독성에 해가 될 수 있겠다 라는 관점도 가질 수 있었어요 :)
몸으로 직접 부딪혀 보면서 많은 관점들을 가져보세요!

2024-06-05 01:26 UTC, Hevton commented on app/build.gradle.kts
> +    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0")
말리빈!! 새로운 시야를 주셔서 감사합니다.
Gson은 non-null 필드에 값이 오지 않을 때 null을 할당하더라도 역직렬화 자체는 예외를 발생시키지 않고, 해당 값을 사용될 때 NullPointerException이 발생하네요.

이에 비해 kotlinx-serialization은 non-null 필드에 값이 오지 않을 때 역직렬화 과정에서 즉시 예외가 발생합니다.
그렇기에 조기에 오류를 발견하고 처리할 수 있다는 장점이 있는 것 같습니다!

2024-06-05 01:30 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/RetrofitDataSource.kt
> +
제 전달이 조금 아쉬웠던 것 같습니다. 하지만 그 덕분에 말리빈의 피드백을 받고 제게 부족했던 비동기 지식에 대해서도 알 수 있게 되었네요. 저는 현재 코드에서도 메인스레드 대신 thread를 열어서 작업을 처리하고 postValue로 값을 반영하기에, 메인스레드가 작업스레드에게 일을 시키고 메인 스레드는 다른 일을 하고 있으므로 enqueue나 AsyncTask가 내부적으로 작업 스레드를 이용하듯이 비동기 요청과 처리를 진행하고 있다고 생각하고 있었는데, 다시금 생각해봐도 비동기 요청이 아니었는지 이해가 잘 되지 않네요. 말리빈께 도움을 요청드리고 싶습니다.

2024-06-05 01:36 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailViewModel.kt
> +    fun setCartProduct(cartProduct: CartProduct?) {
감사합니다 이 부분 수정 진행했습니다

2024-06-05 02:22 UTC, malibinYun approved these changes
원활한 미션 진행을 위해 이만 머지할게요!
피드백은 다음 미션에 반영해주시고, 다음 미션 내용 구현에 더 집중해보세요!

2024-06-05 02:22 UTC, merged

2024-06-05 02:28 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/dto/request/CartItemRequest.kt
> +data class CartItemRequest(
이 부분에 대해서 조금 더 알아봤는데요! 저는 여태 ~Request / ~Response를 관습적으로 생각하고 사용해왔는데,
이외에도 다양한 네이밍을 사용한다는 것을 알게 되었습니다. 그리고 말리빈의 의견을 토대로 Dto 네이밍을 붙여보았습니다!

2024-06-05 02:29 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/RetrofitDataSource.kt
> +
아하~ 이해했어요!
그러면 조금 다른 관점으로 접근해볼게요.
비동기 프로그래밍을 하기 위해 스레드를 이동하는 기능은 View에 데이터를 보여주기 위한 개발을하면서 늘 신경써야하는 부분일까요?
스레드를 이동하는 기능은 정말로 필요한 국소적인 부분에만 적용하고, 상위 단계로 갈 수록 그 기능에 대해 신경쓰지 않도록 구성해보는 건 어떨까요?

enqueue()를 썼을 때, 정의하는 callback 함수 내부에서는 스레드의 이동이 필요했을까요?
thread 이동 관련 코드 없이 enqueue를 활용해보고, 문제가 생길지, 생긴다면 어떤 문제일지, 생기지 않는다면 어떤 문제일지 고민해보세요!
onSuccess에서 바로 view를 수정해보는 것이 하나의 예시가 되겠네요 :)

2024-06-05 02:38 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                            cartAdapter.submitList(it.data)
흐흐 저도 비슷한 생각을 가지고 있어서 공감이 많이 되는군요 😈

> 같이 DataBinding으로 하기 어려운 작업들은 결국 Activity에서 observe 해줘야 할텐데, 

이것도 MVVM 을 엄격히 수호하는 자들은 Activity에 코드를 위치시키지 않더라구요. 엄청나게 신기한 방법을 사용해요.
예를 들면, 실시간 GPS 정보를 가져오는 것, 화면의 해상도가 변경되는 것 (View 의 크기가 유연하게 변경될 때마다 비즈니스 로직에 변경이 생겨야 하는 등의 로직) 등등.. 결국 Context가 필요한 작업 즉, Activity가 관여해야하는 작업임에도 어떻게든 분리하더라구요 ㅎㅎ.. 저는 이렇게 극단적인 걸 별로 좋아하지 않아요.

옛날 네이버 deview에서 MVVM에 대해 발표하신 자료를 공유해 드릴게요. 조금이나마 더 도움이 되는 자료이면 좋겠네요!
https://tv.naver.com/v/4637223?query=mvvm

굉장히 좋은 접근들을 잘 해내시고 있지만!! 다른 시각들도 꼭 챙기면서 "그럴 수 있겠네~" 하는 생각을 많이 가져보기도 하면 좋겠어요 :)

2024-06-05 02:50 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/ProductPagingSource.kt
> +
생각해보니, offset과 pageSize는 외부에서 주입해줘야한다고 생각이 들었습니다.
그래서 이를 적용했습니다!! 감사합니다!

2024-06-05 04:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/dto/request/CartItemRequest.kt
> +data class CartItemRequest(
DTO는 안드로이드 진영에서 잘 사용하지 않는 단어인 것은 참고해주세요!
RestAPI 의 용어를 잘 녹여내보아도 좋겠어요 :)