[쇼핑 장바구니] 호두 1, 2단계 미션 제출합니다.
woowacourse/android-shopping-order pull request #74
Opened 2024-05-30 08:57 UTC by Junyoung-WON

# 쇼핑 장바구니 : 1,2단계 - 비동기, 서버 연동

안녕하세요, 페로로! 오랜만에 인사드립니다.
레벨 2의 마지막 미션을 페로로와 함께하게 된 호두입니다!
마지막 미션인만큼, 최대한 아쉬움이 없도록 열심히 불태워보겠습니다.
불 같은 리뷰도 좋으니 잘 부탁드리겠습니다! 🔥 💪 

## 선택한 JSON 직렬화 라이브러리 : Gson
선택 이유 : 범용성이 높아 많은 개발자가 사용하고, 구현이 간편하고 이해하기도 쉬워서 복잡하지 않은 구현이거나 개발 초기 단계에 많이 사용하는 것으로 알고 있습니다. 빠른 미션 구현을 위해서 Gson을 채택하였습니다!

## 앱 시연 영상

https://github.com/woowacourse/android-shopping-order/assets/92203597/3ebec53d-4f57-44dc-b2c4-ace091316653

## 개선이 필요한 사항들
### 사용자 인증 정보 저장 방법
현재는 Retrofit Service에 하드코딩으로 사용자 정보가 저장되어 있습니다. 😨 
Room DB 또는 SharedPreference같은 로컬 저장소를 활용하여 Email/Password 또는 토큰 값을 저장해야 할 필요성을 느낍니다.
SharedPreference를 사용하여 토큰 값을 저장하도록 구현을 하는 것이 더 좋을 것 같아, 이후 피드백에서 개선해보겠습니다!

### 테스트코드 추가 작성
추가된 ViewModel과 Activity/Fragment에 대한 테스트코드를 추가로 작성해야합니다.

### 스켈레톤 UI와 Thread 접목시키기
지금은 3초의 딜레이를 주어 데이터의 로딩을 기다립니다.(무식합니다..) Thread를 적절히 활용하여서 꼭 개선해보겠습니다.

### 데이터 업데이트 시 UI 깜빡거림 및 전체 데이터 업데이트
일부 데이터와 UI 변경 시 전체 데이터를 모두 변경하는 로직(완전 무식 그 자체입니다...)과 그로인해 리스트 전체가 깜빡거리는 현상이 발생합니다.
일부 데이터만을 변경하도록 메서드를 추가 구현하고 어댑터의 notify 메서드를 적절히 활용하여 개선해보겠습니다.

2024-05-30 11:37 UTC, laco-dev commented
> 앱 시연 영상

수량을 변경시킬 때마다, 전체 아이템을 새로 그리는지 깜빡 깜빡 하는 현상이 있네요.
무엇이 문제일까요?? 혹시 알아보셨을까요?

2024-05-30 12:48 UTC, laco-dev requested changes
데이터 구조와 설계는 잘 나눠주셔서 관심있게 보았습니다.

다만 이번 미션의 핵심 목표인 비동기 프로그래밍으로 구현되어 있지 않아요.
애매하게 코루틴이 섞이면서 제가 잘못 판단하였을 수 있지만, 

데이터 요청 -> 로딩 -> 데이터 불러오기 완료 -> UI 상태 업데이트 라는 하나의 흐름이 보이지 않습니다.

다음 단계에서 코루틴을 활용하기 때문에, 현재는 스레드를 활용한 비동기 프로그래밍으로 올바른 구현으로 리팩토링이 필요해 보입니다.

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/model/dto/ProductResponseDto.kt
> +)
내려주는 값을 그대로 파싱하면 지금처럼 별도로 SerializedName을 사용하지 않아도 되는데요.
서버에서 항상 카멜 케이스로 우리가 원하는 형태로 내려줄지는 아무도 모릅니다.

그렇기에 가급적이면 실수인지 아닌지 명확히 판단하기 위해 `@SerializedName`을 붙여주는 것을 생활화 하면 좋습니다.

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +        }
코루틴을 올바르게 사용하는 것이 아니에요.
3단계 가서 다시 제대로 학습하고 적용하기로 하고 지금은 코루틴 모두 제거해주세요

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +    private val service = ProductClient.service
데이터베이스를 생성자로 넣어주는 것처럼, Retrofit 관련 데이터도 생성자로 넣어주도록 하게 됩니다.
*의존성 역전 및 환경에 따라 다른 인스턴스 주입

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +    private var cartItems: List<CartItem>? = null
서버를 통해서 데이터를 받아오도록 하는게 이번 미션의 핵심 목표인데, 캐시를 이용해 관리하고 처리하는 것은 어떤 용도인가요?

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/domain/model/Order.kt
> +    }
데이터를 어떻게 설계하는지에 따라 다르지만, isChecked 값을 외부 어디서든 접근해서 수정할 수 있다면 의도치 않은 오류가 생길지도 모릅니다.

가령 이런 코드가 있으면 멘붕이 올 수 있죠
```kotlin
val uncheckedCartItem = CartItem().apply { isChecked = true }
```

isChecked 라는 상태가 도메인 타입에 반드시 포함되어야 할 개념인가? 그렇지 않다면 다른 방법은 무엇이 있을까?

```kotlin
class Order(
  val checkedCartItems: List<CartItem>
  ...
)
```

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/domain/repository/CartRepository.kt
> +    fun updateCartItems()
updateCartItems() 이 인터페이스 그리고 내부적으로 사용하는 메모리 정책? 이 어떤 목적이고, 왜 필요한지 설명을 남겨주세요 😓

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/bindingadapters/BindingAdapters.kt
> +}
인자를 넣어주는 방식은 xml에서 바로 사용할 수 있습니다.
```
android:text="@{@string/xxx(argument)}"
```

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +            .commit()
장바구니 화면에서 기기를 회전 해보셨나요??
어떤 일이 발생하는지 supportFragmentManager.fragments 의 로그를 찍어보면서 알려주세요

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                finish()
프래그먼트에도 스택이라는 개념을 사용하게 되는데, 뒤로가기가 다른 프래그먼트를 다시 실행하는게 올바른 흐름인가요?

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        get() = _isEmpty
UI 상태를 정의하는 방법은 여러가지가 있지만, isEmpty()와 RecommendItemState의 Empty가 서로 충돌이 생길 수 있어 보이네요

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        val cartItemIds = cartRepository.findAll().items.map { it.productId }
서버에서 주는 것이라고 가정한다면, 모든 로직이 전부 비동기로 동작할 것으로 예상되는데 뷰모델에 비동기 관련 코드가 보이지 않아서요. 😓

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +    }
더하고 뺴는 동작이, 모든 추천 목록을 다시 불러올 필요까지 있을까요?

필요한 데이터 요청만 하고, UI는 상태를 모두 가지고 있으니 직접 변경할 수 있지 않을까요?

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendationFragment.kt
> +    }
> 스켈레톤 UI와 Thread 접목시키기
지금은 3초의 딜레이를 주어 데이터의 로딩을 기다립니다.(무식합니다..) Thread를 적절히 활용하여서 꼭 개선해보겠습니다.

스켈레톤을 실제 서버 데이터를 요청하는 동안 보여주고, 로딩이 끝나면 풀리도록 만들어주세요.
임의로 스켈레톤을 보이게끔만 하는 날림 코드는 통하지 않습니다. 😠

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/selection/SelectionEventHandler.kt
> +}
UI에 대한 이벤트 핸들러만 담당한다면 가급적 로직을 드러내는 것 보다, 철저하게 UI 중심으로 작성하는 것이 좋습니다.

```kotlin
fun onToggleChecked(...)
fun onItemClick(...)
fun onDeleteClick(...)
```

실제로 아이템을 클릭한다는 행위가 반드시 상세로 이동한다는 것을 의미하지는 않으니까요

2024-05-30 12:48 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/selection/SelectionViewModel.kt
> +        }
마찬가지로 비동기를 이용해, 데이터를 불러오도록 변경이 필요합니다.

2024-05-31 06:44 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +object ProductClient {
서버 환경 또한 변경이 가능하다면, 레포지토리를 만들어 사용할 때 처럼, 서버의 연결이나 통신에 관한 Interface를 정의해서 활용할 수 있을 것 같습니다.
지금은 레포지토리 구현체에서 서버 Client를 직접 참조하여 서버 정보를 주고받는데, interface를 활용해서 리팩터링을 시도해볼 수 있겠네요.

2024-05-31 06:57 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +            }
오늘 오전 수업에서 코루틴에 대해 배웠습니다.
코루틴에 대해서 아직 잘 이해한 것은 아니지만, 수업을 듣고 해당 코드를 다시 보니 정말 이상하게 사용하고 있었다는 것을 깨달았습니다. 😱 
페로로가 말씀해주신 runBlocking 블럭과, launch 메서드 대신 예상되는 반환 값을 필요로하므로 async, await을 활용하면 해결할 수 있겠습니다...!

하지만 지금은 코루틴을 사용하지 않으니, CountDownLatch를 활용해볼 수 있을 것 같습니다. 수정하겠습니다!

2024-05-31 07:12 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/data/model/dto/Pageable.kt
> +package woowacourse.shopping.data.model.dto
서버로부터 장바구니의 아이템 목록과 상품 목록을 받을 때 날아오는 Json 데이터 중 "pageable" 이라는 항목이 존재합니다! 받은 Json response를 역직렬화가 가능하도록 `Pageable`이라는 DTO를 만들었습니다.
아래는 서버에서 날아오는 상품 목록 Json 데이터의 예시입니다.

```
{
  "content": [
    {
      "id": 2,
      "name": "나이키",
      "price": 1000,
      "imageUrl": "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a28864e3-de02-48bb-b861-9c592bc9a68b/%EB%B6%81-1-ep-%EB%86%8D%EA%B5%AC%ED%99%94-UOp6QQvg.png",
      "category": "fashion"
    },
    {
      "id": 3,
      "name": "아디다스",
      "price": 2000,
      "imageUrl": "https://sitem.ssgcdn.com/74/25/04/item/1000373042574_i1_750.jpg",
      "category": "fashion"
    }
  ],
  "pageable": {
    "sort": {
      "sorted": false,
      "unsorted": true,
      "empty": true
    },
    "pageNumber": 0,
    "pageSize": 2,
    "offset": 0,
    "paged": true,
    "unpaged": false
  },
  "last": false,
  "totalPages": 77,
  "totalElements": 154,
  "sort": {
    "sorted": false,
    "unsorted": true,
    "empty": true
  },
  "first": true,
  "number": 0,
  "numberOfElements": 2,
  "size": 2,
  "empty": false
}
```

2024-05-31 07:39 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +        }
어째 페로로에게 리뷰를 받는 미션마다 코루틴 사용을 남발하는 것 같습니다...
오목 미션때에도 코루틴을 썼었더랬죠.. 😢 
Thread를 잘 활용해서 고쳐보겠습니다.

2024-05-31 08:03 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/domain/model/Order.kt
> +    }
UI에서 해당 아이템이 체크되었는지 여부를 확인하는 용도만으로 사용되는 것 같네요.
View에서의 사용자 동작으로 Order에 아이템이 추가, 삭제되는 로직만으로도 충분한 것 같고, isChecked라는 상태는 도메인에서는 꼭 필요한 개념이 아닌 것 같습니다.

2024-05-31 08:06 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +    private var cartItems: List<CartItem>? = null
매번 서버를 통해 데이터를 새로 불러오는 것이 불필요한 요청을 보내는 것이고, 좋은 구현은 아닐 것이라는 생각 때문에 캐시를 사용했던 것 같습니다.

2024-05-31 08:15 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/domain/repository/CartRepository.kt
> +    fun updateCartItems()
레포지토리를 이용하여 데이터들을 불러올 때, 최초에 가져온 데이터 목록을 1회성으로만 사용(View에 나타내기 위함)하기보다는, 한번 가져왔던 데이터들을 내부적으로 저장하여 재사용한다면 불필요한 서버 통신을 줄이고 빠른 동작을 이끌어낼 수 있을 것이라는 생각이 들었습니다. 위에서도 질문주신 부분과 동일한 이유입니다.

- 목적: 데이터 재사용(재활용)
- 이유: 빠른 동작 처리, 불필요한 서버 요청 감소

2024-05-31 08:23 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/bindingadapters/BindingAdapters.kt
> +}
위 방식을 시도했었는데 계속 빨간줄이 나타나서.. '안되는거구나' 하고 바인딩 어댑터를 사용했었습니다.
페로로가 주신 코드를 보고 다시 작성해보니 잘 적용되는군요... 왜 안됐었는지 다시 확인해보니
`@strings/xxx` 라고 `string`에 's'를 붙였었네요. 😂 
저는 바보입니다.

2024-05-31 09:17 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        get() = _isEmpty
이전에 RecommendItemState가 비어있다가 (isEmpty == true) 다시 데이터를 받았을 때 isEmpty가 여전이 true일 수 있겠네요.
State에 Empty라는 상태를 추가하거나, isEmpty가 RecommendedItems를 항상 참조하고 있도록 수정이 필요하겠군요.

2024-05-31 09:25 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/model/dto/Pageable.kt
> +package woowacourse.shopping.data.model.dto
`PageableDto` 가 있는 시점에서 `Pageable`이 있어 오해의 소지가 있었던 것 같습니다.
이건 json을 파싱해서 객체를 만들다가 실수로 추가된 내용입니다.
기존에 `PageableDto`를 활용했어야 했는데, 제대로 확인하지 못하고 똑같은 dto 객체를 만들었습니다.

@Junyoung-WON 
`CartItemDto` 의 `val pageable`을 Pageable -> PageableDto 로 변경하고, 해당 `Pageable`객체는 삭제하면 될 것 같습니다.

2024-06-05 06:29 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +            .commit()
화면을 회전했을 경우, Activity가 새로 onCreate 되면서 새로운 selectionFragment를 또 추가하게 됩니다.
`supportFragmentManager.fragments`를 Log 로 찍어보니, `SelectionFragment`가 2개가 있는 것을 확인할 수 있었습니다.
기존에 있었던 Fragment 위에 또 add를 하면서, 마치 잔상이 남는 것 처럼 2개의 Fragment가 겹쳐져서 보이게 되네요.
이는 드래그를 하거나 상품 수량 변경, 상품 삭제를 하면서 알게 되었습니다.

다음 화면인 상품 추천 화면에서도 화면 회전 시, 역시나 CartActivity가 또 다른 `SelectionFragment`를 add 하게 되어 
`RecommendationFragment`와 `SelectionFragment`가 겹쳐 보이는 현상이 발생했습니다.
CartActivity의 `supportFragmentManager.fragments` 에서는 [RecommentFragment, SelectionFragment] 순서로 프래그먼트가 쌓여있었고, 사용자에 의해 동작하는 프래그먼트는 최근에 생성되어 add된, 제일 상위에 있는 SelectionFragment였습니다.

2024-06-05 07:12 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                finish()
프래그먼트가 리스트에 스택처럼 쌓이는 특성을 활용하여 개선해보았습니다.

우선 `CartActivity`가 Fragment의 전환을 관리하는 것이 좋을 것 같아, Fragment의 추가, 삭제와 show, hide를 Activity의 로직으로 모았습니다. `FragmentController`라는 인터페이스를 생성하여, 프래그먼트에서의 동작(여기서는 주문하기 버튼)에 따라 Activity가 적절한 Fragment로 교체할 수 있도록 구현했습니다. 이 인터페이스의 동작은 `CartActivity`가 상속받아 구현합니다.

```kotlin
interface FragmentController {
    fun onBackButtonClicked()

    fun onOrderButtonClicked()
}

```


주문하기 버튼 클릭이나, 뒤로가기 버튼의 클릭 마다 새로운 Fragment로 replace하는 것 대신,
새 Fragment를 add, remove하고 기존 Fragment를 show, hide하는 것으로 변경했습니다.
주문하기 버튼을 클릭했을 때 `SelectionFragment`를 잠시 `hide()`하고, `RecommendationFragment`에서 뒤로가기를 눌렀을 때 `hide()`되었던 `SelectionFragment`를 다시 `show()`하여 나타내도록 수정해보았습니다.

```kotlin
    override fun onOrderButtonClicked() {
        when (val topFragment = supportFragmentManager.fragments.lastOrNull()) {
            // 현재 Fragment(SelectionFragment)를 숨기고 RecommendationFragment 추가
            is SelectionFragment -> {
                supportFragmentManager.beginTransaction()
                    .hide(topFragment)
                    .add(R.id.cart_fragment, RecommendationFragment())
                    .setReorderingAllowed(true)
                    .commit()
            }

           ...
 
        }
    }
```

```kotlin
    override fun onBackButtonClicked() {
        when (val topFragment = supportFragmentManager.fragments.lastOrNull()) {
            is SelectionFragment -> {
                supportFragmentManager.beginTransaction()
                    .remove(topFragment)
                    .setReorderingAllowed(true)
                    .commit()
                finish()
            }

            is RecommendationFragment -> {
                // 현재 Fragment(RecommendationFragment)를 제거하고 숨겨진 SelectionFragment 출력
                supportFragmentManager.beginTransaction()
                    .remove(topFragment)
                    .show(selectionFragment)
                    .setReorderingAllowed(true)
                    .commit()
            }

            else -> {
                finish()
            }
        }
    }
```

2024-06-05 07:14 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        get() = _isEmpty
`MediatorLivaData`를 활용하여, `LivaData`인 `RecommendItemsState`가 비어있는지 여부에 따라 자동으로 isEmpty의 값 또한 변경되도록 개선했습니다.

2024-06-05 07:16 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/selection/SelectionEventHandler.kt
> +}
네이밍으로 내부 동작을 드러낸다면, 이후에 다른 동작으로 변경되었을 때 리팩터링이 어려워지겠군요!
UI의 동작만을 나타내도록 네이밍 수정하였습니다!

2024-06-05 07:22 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +            .commit()
`onCreate()` 시에 `savedInstanceState`가 `null`인 경우에, 즉 최초에 Activity가 생성된 경우에는 `supportFragmentManager`를 이용해 `SelectionFragment`를 add 하도록 하였습니다.
이후에 config change가 일어나게 되면 `savedInstanceState`는 null이 아니므로,
Activity가 또 다시 `SelectionFragment`를 add 하는 동작이 일어나지 않아 위와 같은 현상을 개선할 수 있었습니다.

```kotlin
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        ...

        setupInitialFragment(savedInstanceState)
    }

    private fun setupInitialFragment(savedInstanceState: Bundle?) {
        if (savedInstanceState == null) {
            supportFragmentManager.beginTransaction()
                .add(R.id.cart_fragment, selectionFragment)
                .commit()
        }
    }

```

2024-06-05 07:25 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendationFragment.kt
> +    }
이 또한 수정하였습니다! 😄
비동기에 관련한 개선 사항은 추가 PR 코멘트에서 상세히 작성해보겠습니다.

2024-06-05 07:27 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/domain/model/Order.kt
> +    }
결국에는 UI에서 체크박스의 체크 상태가 필요했기에, UIModel을 새로 작성하여 이를 LiveData에 활용하였습니다.
이를 도메인 로직과 일치시키는 작업이 추가로 필요하여 코드가 조금 복잡해졌지만, `CartItem` 도메인 모델에서는 isChecked 라는 상태를 가지지 않게 되었습니다.

2024-06-05 10:47 UTC, Junyoung-WON commented
안녕하세요, 페로로! 오랜만에 다시 인사드려요!
기능 구현과 비동기 처리로 개선하는 리팩터링을 끝내고 뒤늦게 PR을 보내드립니다!
아래에는 큰 주요 변경 사항을 정리하여 적어보았습니다.

---
## 변경 사항

### 리스트 변경 시 깜빡거림 현상 제거
notify를 사용하여 어댑터에게 데이터 변경을 알릴 때, payload라는 추가 인자를 활용하여 변경된 부분에 대해서만 바인딩 데이터를 업데이트하도록 개선했습니다.
이 과정에서 뷰모델에 수량, 체크 상태 등이 변경된 데이터임을 저장하는 LiveData를 추가하여, Activity나 Fragment가 이를 확인해서 adapter에게 넘겨주는 로직이 추가되었습니다.
ListAdapter를 사용하는 방법도 크루들에게 들었습니다만, 리팩터링이 오래 걸릴 것 같아 이후에 여유가 있을 때 적용해보고자 합니다.

### Repository 리팩터링 - 서버와의 비동기 데이터 요청/처리
Retrofit Service의 `enqueue()` 메서드를 활용하여 비동기적으로 데이터를 요청하고 이를 처리할 수 있었습니다.
상품 목록이나 상품, 장바구니 아이템 등 동기적인 작업이 필요하다고 생각한 부분을 제외하고서는 대부분 enqueue() 메서드로 비동기 작업을 통해 데이터를 요청합니다.
데이터를 성공적으로 불러오면 callback 함수의 인자로 해당 데이터를 넘겨주고, 넘겨줄 때 Result 로 감싸면서 예외 처리도 함께 진행했습니다.

### 장바구니 화면에서 Fragment 관리
이전에 구현에서는 장바구니 화면에서 화면을 회전할 경우 SelectionFragment가 또 추가되어 UI가 중첩되는 현상이 발생했습니다.
그리고 list 형태로 스택처럼 쌓이는 Fragment를 단순히 replace 하는 동작으로 처리되었습니다.
savedInstanceState를 체크하여 null인 경우에만 SelectionFragment를 추가하도록 수정했고, Fragment의 추가, 삭제 로직을 Activity가 담당하며 show, hide를 활용하여 Fragment의 교체를 개선했습니다.

### 장바구니 전체 선택 로직 수정
장바구니 화면에서 전체 선택 시에 아이템의 체크 상태가 제대로 나오지 않는 오류를 수정했습니다.

## 추가로 개선이 필요한 부분들

### 테스트 코드 수정
많은 코드들을 수정하다보니 테스트 코드에서도 많은 리팩터링이 필요했습니다.
특히 뷰모델과 레포지토리의 로직이 많이 변경되어서, 비동기 처리 등에 관련하여 테스트 코드를 수정할 필요가 있습니다.

### Service 리팩터링 필요
사용자 인증 정보를 저장하는 로직과 서버와의 연결을 위해 client를 생성하는 로직의 리팩터링을 아직 진행하지 못했습니다.
어떻게 하면 서버를 변경할 때에도 유리할지, 또 어떻게 해야 사용자 인증 정보를 주입시키는 것도 편리할 지 고민을 더 해볼 필요가 있습니다.

2024-06-06 07:54 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/model/dto/ProductResponseDto.kt
> +)
이거는 팀마다 다릅니다 :)

2024-06-06 07:55 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteCartRepositoryImpl.kt
> +    private var cartItems: List<CartItem>? = null
디테일한 요소를 챙기는 것도 좋지만, 네트워크에 집중해도 충분하지 않았을까 싶어요.
중요하지 않은 부분까지 모두 맥락을 확인하면서 보기에는 어려울 수도 있으니까요.

2024-06-06 07:56 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/domain/repository/CartRepository.kt
> +    fun updateCartItems()
그건 데이터 내부적으로 처리할 일이지, 인터페이스로 노출될 이유가 없지 않을까요?

2024-06-06 08:07 UTC, laco-dev approved these changes
피드백 반영 고생 많으셨습니다.

프래그먼트나 캐시를 활용하여 여러가지 디테일을 챙기고 싶어 한 것 같지만,
반대로 이로 인해 많은 리소스 분산이 발생하게 되었습니다.

코드가 더욱 복잡해지기도 하고, 리뷰에 있어서도 중요한 포인트를 놓치고 미션과 관련없는 커뮤니케이션이 발생하니까요.

현업에서도 마찬가지이지만, 우선 목표를 위한 가장 최선의 구현을 선택한 이후 그 다음에서야 디테일 요소나 최적화를 고민 하는 것이 좋습니다.
물론 처음부터 다 챙기면 좋지만, 아직은 그럴 정도의 경험이 많이 부족하니까요.

이번 미션의 핵심 요소인 네트워크와 비동기를 연습해야 하는데 다른거에 많이 시간이 뺏긴건 아닌지 고민 해보시면 어느정도 생각이 드실 겁니다.

다음 미션을 통해, 다시 한번 비동기를 제대로 사용할 수 있는지 경험하기 때문에 다른 피드백은 남기지 않았습니다. :)

호두가 그렇게 바라던 코루틴 기대하겠습니다.

2024-06-06 08:07 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteShoppingRepositoryImpl.kt
> +    ): Result<ProductListInfo> {
스레드를 이용한 비동기 통신이라면, 콜백 함수를 통해 주고 받는게 정석입니다.
지금의 경우는 비동기처럼 보이지만, 그냥 join()을 사용한 동기 함수와 차이가 없으니까요.

코루틴을 활용하면 또 다르지만, 스레드의 경우는 아래와 같이 콜백을 사용할 수 있습니다.
```kotlin
fun fetchProductsWithPage(
  page: Int,
  size: Int,
  onResult: (Result<ProductListInfo> -> Unit)
) { ... }
```

2024-06-06 08:07 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        }
하나의 소스만 사용하고 있다면 MediatorLiveData가 의미가 크게 없어보이네요!?

2024-06-06 08:07 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        if (recentProduct != null) {
지금 같은 경우에도 코드가 길어지고 깊어진다면, early return으로 먼저 끊고 명확하게 나누는 것도 도움이 됩니다.

```kotlin
if (recentProduct == null) {
  ...
  return
}
...
```

2024-06-06 08:07 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/selection/SelectionFragment.kt
> +        viewModel.setUpCartItems()
onResume()은 언제 호출이 되나요??

onResume() 마다 매번 아이템을 초기화 하는 것이 좋은 방향일까요?

2024-06-06 08:08 UTC, merged

2024-06-06 10:07 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        }
그렇네요... 여러 개의 LiveData로부터 또 다른 상태를 나타내는 LiveData를 활용할 때 사용하기 좋은게 MeiatorLiveData인데, 그 장점을 잘 활용하는 코드가 아니었군요.

2024-06-06 10:10 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/recommendation/RecommendViewModel.kt
> +        if (recentProduct != null) {
원하지 않는 상황일 때 return을 일찍 하도록 작성한 코드가 그 동작이 더 잘 보이는군요!
참고해서 수정해보겠습니다!!

2024-06-06 10:17 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/selection/SelectionFragment.kt
> +        viewModel.setUpCartItems()
onResume()은 View가 화면에 나타나기 시작한 후(onStart() 이후)에 호출됩니다...!
화면이 전환되어 View가 그려질 때 마다 장바구니 아이템들을 새로 불러오니, 상당히 비효율적이겠네요.
지난 미션 때 배운 Activity의 result api를 활용해서 다른 View가 종료된 후의 결과를 받아 업데이트할 수 있도록 한다면 이런 불필요한 로딩이 줄어들 것 같습니다.

우선 페로로 말씀처럼, 비동기 처리와 서버와의 네트워크 기능을 배우는 데에 집중하여 미션을 진행하겠습니다.
이후에 혹시라도 여유가 되면 개선해보겠습니다! 😄 🚀

2024-06-10 04:47 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/data/database/ProductClient.kt
> +        private val email = "junyoung-won"
local.properties와 BuildConfig를 활용하여서 서버 정보나 API키, 아이디 및 비밀번호와 같은 민감 정보들을 로컬 개발 환경에서만 저장하고 사용할 수 있음을 알 수 있었습니다.
이런 민감 정보가 깃헙에 그대로 공유된다면, 정말로 파국이 되겠네요.... 😱

2024-06-10 04:55 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/data/repository/RemoteShoppingRepositoryImpl.kt
> +    ): Result<ProductListInfo> {
뒤늦게 구현 의도에 대해 답장을 드리자면, 해당 부분은 의도적으로 동기 함수로 작성했었습니다!
단순히 상품 정보만을 불러오는 것이 아니라, 상품 리스트와 함께 장바구니 아이템들의 정보들을 함께 결합하여 상품 목록 화면 데이터를 구성하는 구현으로 선택했었습니다.
때문에 불가피하게 장바구니 아이템이 불러오기 전에 꼭 상품 정보가 필요해야 했기에, 동기적으로 상품 정보를 불러오는 것을 택했습니다.

코루틴으로 리팩터링을 진행한 지금도 상품 리스트와 장바구니 아이템 정보를 결합하여 상품 목록 화면의 데이터를 구성하는 구현 방식은 그대로입니다.
하지만 이번에는 코루틴의 async와 await을 활용하여, 두 정보 모두 비동기적으로 요청하되, 두 데이터를 결합할 때 까지 요청을 await 하여서 원하는 데이터 변환 동작을 정상적으로 이뤄낼 수 있었습니다.