[쇼핑 주문] 올리브 3, 4 단계 미션 제출합니다.
woowacourse/android-shopping-order pull request #79
Opened 2024-06-08 10:01 UTC by kimhm0728

안녕하세요 파이로! 3, 4단계 구현하여 리뷰 요청 드립니다.
이번 리뷰도 잘 부탁드립니다. 🙂

현재 Ui 테스트가 실행할 때마다 결과가 달라지고 있습니다..
코루틴을 적용하면서 비동기 타이밍이 맞지 않아 생기는 문제 같습니다.
액티비티 생성자로 Repository를 주입받아서, 테스트 환경에서는 FakeRepository를 넣어주도록 수정하고 싶은데요.
여러 자료를 찾아봐도 DI 라이브러리를 사용하는 방법밖에 나오질 않네요..
DI 라이브러리를 사용하는 것은 현재 단계에 맞지 않는 것 같아서 아직 적용하지 못했습니다. 😢
라이브러리를 사용하지 않으면서, Ui 테스트가 타이밍에 구애받지 않고 항상 통과할 수 있으려면 어떻게 해야할지 조언 부탁드릴 수 있을까요???

감사합니다!!!!

[시연 영상 링크](https://drive.google.com/file/d/11nW23hzELXA_1QRx28WgsyXsGA1HPbFj/view?usp=sharing)

2024-06-08 15:08 UTC, ghojeong requested changes
본격적으로 리뷰를 시작하기 전, Ui 테스트에 관한 올리브의 질문에 먼저 대답을 해보았습니다.
현재 레벨에서 제 조언은 다음과 같습니다.

1. DI 에 욕심내기 보다는, 코루틴에 집중하자.
2. Ui 테스트에 욕심내기 보다는, ViewModel 과 domain 모델의 테스트에 집중하자.

2024-06-08 15:08 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/domain/model/FreeShippingCoupon.kt
> +}
현재 FreeShippingCoupon 과 PercentageCoupon 도메인 모델에 대해서는 테스트가 전혀 작성되어 있지 않는듯 한데,
테스트할 필요가 있는 모든 도메인 모델에 대해서 테스트 보완해주시기 바랍니다.

또한 RecentProduct 에서 seenDateTime 가 전혀 활용되고 있지 않는 듯 한데,
확인 부탁드립니다.

2024-06-08 16:12 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>          }
> 확실하게 성공 혹은 실패 시에 isLoading 이 false 가 되어야 한다고 생각하는데, 어떻게 생각하시나요?

그런데 launch {} 라는 `CoroutineScope` 내에서는, cartRepository의 비동기 작업이 얼마나 걸리든 항상 순차적으로 실행된다고 이해했습니다. 

<img width="1027" alt="스크린샷 2024-06-09 오전 12 28 43" src="https://github.com/woowacourse/android-shopping-order/assets/70271235/971ee387-bf5e-4671-8122-55d9fca458d9">

실제로 `cartRepository.findAll()` 내부에서 `delay(5000)`을 주고, 위 사진과 같이 로그를 찍어보았는데요. 항상 cartItems가 불러온 이후에 isLoading이 false가 된 것을 확인할 수 있었습니다!

처음에는 onSuccess, onFailure 블럭 내부에서 isLoading을 false로 명시해주었는데, 동일한 코드가 중복되는 것을 줄이기 위해 현재와 같이 작성했습니다. 🙂 혹시 제가 파이로 코멘트를 잘못 이해한 부분이 있다면 말씀해주세요!!

2024-06-08 16:13 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/products/ProductsViewModel.kt
>          }
isLoading에 대한 제 의견은 [위 코멘트](https://github.com/woowacourse/android-shopping-order/pull/79#discussion_r1632067385)에 남겨두었습니다.
그런데 현재 코드에서는 products를 불러오는 작업이 실패하는 경우에도 isLastPage를 불러오고 있네요.. products를 제대로 불러온 경우에만 `loadIsPageLast()`를 호출하는 것이 적절하다고 생각해서 수정했습니다! [eadd305](https://github.com/woowacourse/android-shopping-order/pull/79/commits/eadd30559481c23f0aef40221e00e39c7e720a00)

2024-06-08 16:23 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/domain/model/FreeShippingCoupon.kt
> +}
> 또한 RecentProduct 에서 seenDateTime 가 전혀 활용되고 있지 않는 듯 한데,

Room repository에서 가장 마지막으로 본 상품을 조회하거나, 최근 본 상품을 시간 순서대로 정렬하기 위해 seenDateTime 프로퍼티를 추가했었습니다.
기존에는 도메인 모델의 RecentProduct와 Room에서 사용되는 Entity 모델을 구분하지 않았기 때문에 도메인 모델의 seenDateTime이 Room에서 사용되고 있었는데요. 도메인 모델과 Room Entity 모델을 분리하는 리팩터링을 하면서, 도메인 모델의 seenDateTime를 제거해주지 않았네요...

또한 추후 기능이 확장되면, data source에서 받아오는 entity, dto 등이 아닌 도메인 모델 RecentProduct에서도 seenDateTime를 활용할 수 있을 거라고 생각해서 남겨두었습니다.

그런데 seenDateTime으로 어떤 값을 계산하는 것은 data source에서 해야 할 일이기 때문에, 도메인 모델에서는 불필요한 것 같습니다. seenDateTime 프로퍼티를 제거했습니다!! [ba48056](https://github.com/woowacourse/android-shopping-order/pull/79/commits/ba480563d7a14c6482483ed9339472af85a3f876)

2024-06-08 16:24 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/domain/model/FreeShippingCoupon.kt
> +}
> 테스트할 필요가 있는 모든 도메인 모델에 대해서 테스트 보완해주시기 바랍니다.

추가했습니다!!
- FreeShippingCoupon [3a38ada](https://github.com/woowacourse/android-shopping-order/pull/79/commits/3a38ada96e504ab7eb93a8de442634fa05d097e9)
- PercentageCoupon [c56d900](https://github.com/woowacourse/android-shopping-order/pull/79/commits/c56d900b044a5ad37a56141ce7dd12af048038c5)
- CartItem [ad1471f](https://github.com/woowacourse/android-shopping-order/pull/79/commits/ad1471fa1a36d23c45946770a32f1e8d180b76ea)

2024-06-08 16:27 UTC, kimhm0728 commented on app/src/test/java/woowacourse/shopping/fake/FakeCartRepository.kt
>      }
앗!! 실제 코드는 비동기인데 ui 테스트에서는 동기적인 코드라고 가정한 코드를 작성하고 있었네요.
파이로 코멘트를 읽으니 제가 겪고 있는 문제가 무엇인지 확 와닿았습니다......... 😭

2024-06-08 16:57 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>          }
> 처음에는 onSuccess, onFailure 블럭 내부에서 isLoading을 false로 명시해주었는데, 동일한 코드가 중복되는 것을 줄이기 위해 현재와 같이 작성했습니다.

onSuccess 와 onFailure 블럭 내부에 있던 `_isLoadingCart.value = false` 를 바깥으로 빼낸 것에 대해 
이해를 하시고 빼낸 것인지 궁금해서 낚시 질문을 던져보았는데 매우 훌륭하게 답변을 해주셨습니다. 💯 👍 

잡담 질문 스레드에 정리해주신 답변이 훌륭해서 저도 장난을 쳐보고 싶어졌었네요 ㅋㅋㅋㅋ
실제 로그까지 찍어보시면서 확인해주셔서 감사합니다. 💯

2024-06-08 17:28 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>          }
앗 ㅋㅋㅋ 스레드 답변을 좋게 봐주신 것 같아서 뿌듯하네요 ㅎㅎ

> 로딩이 끝났는지 확인 후 상품 목록이 보이는 지 확인하는 과정이 테스트할 때 추가로 필요하다고 생각합니다.

이 부분 관련해서 고민 중인데요 😭
코멘트를 읽어보니 `장바구니 아이템을 불러오기 전 스켈레톤이 보인다`, `장바구니 아이템을 불러오면 상품 목록이 보인다`와 같은 두개의 시나리오를 테스트할 수 있을 것 같습니다.

그런데 현재 실패하고 있는 Fragment 테스트에서 isLoading 여부에 따른 시나리오를 작성해보라고 말씀하신 것이 맞을까요?!?!?

이것 관련해서 여러가지 시도를 해보고 있긴 한데..... 
Fragment Test에서 코루틴, viewModel을 제어하려다보니 unit test와 가까운 테스트가 되어버리는 것 같아서요..!!

모든 ui 상태들은 viewModel이 가지고 있기 때문에 ui 테스트를 어떤 식으로/어떤 범위까지 해야할지가 어렵습니다..... 
저도 파이로의 코멘트처럼, ui 테스트에 너무 힘을 들이기 보다는, viewModel 테스트에서 비즈니스 로직을 테스트하는 것이 맞다고 생각합니다. 그런데 데이터가 로드되었는지에 따라 화면에 그려지는 뷰가 달라지기 때문에, 정말 기본적인 뷰 visible/gone 테스트도 까다로워졌네요... 제가 너무 어렵게 생각하는 건지, 방향을 잘못 잡고 있는 건지 모르겠습니다 🤔🤔

2024-06-08 17:34 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>          }
> 두개의 시나리오를 테스트할 수 있을 것 같습니다.

오오! 안 그래도 다음 리뷰 때 언급하려고 했는데,
먼저 말씀해주시다니 좋네요. 👍 

> Fragment Test에서 코루틴, viewModel을 제어하려다보니 unit test와 가까운 테스트가 되어버리는 것 같아서요..!!

사실 그렇기 때문에, 저도 ViewModel 과 도메인 객체 테스트만 잘한다면,
Ui 테스트는 굳이 하지 않아도 된다고 생각하는 편입니다.
실무 관점에서도 Ui 테스트는 테스트 시 컴퓨팅 리소스를 많이 잡아먹기 때문에,
꼭 필요한 Ui 테스트가 아니라면 저도 굳이 권장하지는 않습니다.

2024-06-08 17:44 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>          }
> 그런데 데이터가 로드되었는지에 따라 화면에 그려지는 뷰가 달라지기 때문에, 정말 기본적인 뷰 visible/gone 테스트도 까다로워졌네요...

제가 도전해보라고 한 것은 이 테스트가 까다롭고 어려운게 맞기 때문에,
코루틴과 비동기에 대해서 학습을 해볼만한 도전과제로 도전해보라는 의미였습니다. 😄 

뷰에 대한 테스트가 까다롭다는 것을 인지하고 나면, 테스트가 필요한 비즈니스 로직은 
반드시 ViewModel 과 도메인 모델로 옮겨야 한다는 생각이 들지요 ㅋㅋㅋㅋㅋ
사실 뷰에 대한 테스트는 보통 어렵고 까다로워서 실무에서도 잘 작성 안하게 된다는 게 제가 말하고 싶은 바였습니다.
(저는 그렇습니다. 저보다 훨씬 잘하시는 분들은 Ui 테스트까지 꼼꼼하게 작성하실 수도 있습니다.)

저는 두개의 테스트 시나리오를 분리해내셨다는 점에서, 제가 처음에 원했던 의도에서 충분하다고 생각합니다.
ViewModel 에서 해당 시나리오를 테스트하는 것으로 끝내셔도 됩니다.

2024-06-08 17:47 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>          }
그러면 말씀드린 두 시나리오는 뷰모델 테스트에 추가해 보겠습니다..!! 뷰모델 테스트 보완 후 다시 리뷰 요청드리겠습니다.
늦은 시간에도 답변 주셔서 너무 감사합니다. ㅎㅎ 🙇

2024-06-09 08:10 UTC, kimhm0728 commented
@ghojeong 파이로 안녕하세요! 뷰모델 테스트 보완하여 리뷰 요청 드립니다.
mock과 delay를 사용해서 테스트는 통과시켰는데....... 적절한 방식은 아닌 것 같다는 생각이 드네요 😭
뷰모델 내 launch 실행이 끝나기 전의 상태를 어떻게 테스트해야 할지가 어렵습니다 💦

여기에 많은 시간을 쏟기보다는,, 3, 4 단계 미션인 코루틴/쿠폰 에 대한 피드백을 받고 싶어서 리뷰 요청 드리게 되었습니다!
이번 리뷰도 잘 부탁드립니다!

2024-06-09 14:17 UTC, ghojeong requested changes
올리브!
통과하지 못하는 단위 테스트를 발견했는데,
확인 부탁드립니다.

2024-06-09 14:17 UTC, ghojeong commented on app/src/test/java/woowacourse/shopping/domain/model/PercentageCouponTest.kt
> +    }
<img width="999" alt="스크린샷 2024-06-09 오후 11 15 34" src="https://github.com/woowacourse/android-shopping-order/assets/38595650/bc1a5e7d-1c76-4792-af49-f45c5c4466e1">

2024-06-09 15:05 UTC, ghojeong requested changes
올리브
공부를 열심히 해주셔서인지, 코루틴과 바인딩에 익숙해지셨다는게 느껴지네요.
칭찬 위주로 피드백 남겨보았습니다. 😄

2024-06-10 06:29 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/products/ProductsViewModel.kt
`productUiModels()` 내부에서 `_productUiModels`가 null이면 emptyList()를 반환해서, `loadProducts()`에서 바로 return해주는 경우가 없도록 수정했습니다! [58ae9d8](https://github.com/woowacourse/android-shopping-order/pull/79/commits/58ae9d89e80fa5fa3038a59c7d7d77c4742fed08)

2024-06-10 06:57 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>      }
넵!! 선택된 장바구니 상품들의 아이디를 셋팅해주는 함수이기 때문에, 함수명에 이러한 의미가 내포되도록 수정했습니다. [fe03bff](https://github.com/woowacourse/android-shopping-order/pull/79/commits/fe03bff230eaa9ee56451770a5650c163745dbdc)

2024-06-10 08:04 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +                    updateCart()
앗 그렇네요!! updateCart() 내부에서 totalPrice, totalQuantity, selectedCartItemCount 를 update해주고 있었는데요. 각각의 LiveData들을 cartUiModels.map 을 통해 직접 변경하도록 수정했습니다. 코드를 확 줄일 수 있네요... ㅎㅎ 감사합니다! [a69b2c0](https://github.com/woowacourse/android-shopping-order/pull/79/commits/a69b2c0e7355afaf78670dacd67d6fa33990e81f)

2024-06-10 08:15 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +            _changedCartEvent.value = Event(Unit)
음.... `_changedCartEvent`가 존재하는 이유는, 장바구니 화면에서 상품 목록으로 다시 돌아왔을 때, 변경된 장바구니 상품들의 데이터들을 반영하기 위해서입니다. 만약에 장바구니 화면에서 아무것도 변경하지 않았는데, 상품 목록 화면에서 모든 데이터를 다시 로드하다면 비효율적이라고 생각되어서, 장바구니 화면에서 변경사항이 발생했을 경우에만 로드하도록 구현했습니다.

그래서 장바구니 상품이 추가되거나, 삭제되거나, 수량이 변경되었을 경우 `_changedCartEvent.value = Event(Unit)`를 호출했습니다. 그런데 상품 추가/삭제/변경이 실패하는 경우에도 event에 값을 대입해주고 있었네요... 💦 onSuccess 시에만 호출하도록 수정했습니다! [1d89809](https://github.com/woowacourse/android-shopping-order/pull/79/commits/1d8980990fa1c4b9be6019ec936aefe3480d7feb)

아니면 `_changedCartEvent` 라는 네이밍이 직관적이지 못하다는 의미일까요????

2024-06-10 08:43 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/data/coupon/remote/Mapper.kt
> +        LocalDate.parse(expirationDate) ?: throw IllegalArgumentException(INVALID_COUPON_DTO_PARAMETER),
이 부분을 어떻게 개선할지 아직 감을 못 잡았습니다 😢 
어떤 매개변수가 null인지에 따라 exception을 달리 하라는 말씀이신가요?
아니면 매개변수가 null인 경우의 exception과 다른 경우의 exception을 구분하라는 말씀이신가요???

2024-06-10 08:53 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/ui/products/ProductsViewModel.kt
잘 해주셨네요 👍 
저도 마찬가지로 에러 상황에 맞게 exception 을 viewModel 에서 분기시키고, 
view 에서 에러에 따른 화면 처리를 해줍니다. 
말씀해주신 것처럼 서버 통신에러는 굳이 세세하게 메세지를 나누지는 않고,  (예: 삭제했는데 어떤 서버에러 때문에 발생했는지) 
그 행위에 대한 에러 처리만 합니다 (예: 삭제에 실패했습니다 다시 시도하세요). 
서버 통신 에러는 주로 디버깅이나 crashlytics 에서 확인용으로 exception 을 나눠둡니다.

2024-06-10 09:06 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +            _changedCartEvent.value = Event(Unit)
> 장바구니 화면에서 변경사항이 발생했을 경우에만 로드하도록 구현했습니다.
>  onSuccess 시에만 호출하도록 수정했습니다!

잘하셨습니다. 👍 
제가 수정을 원했던 의도와 일치합니다!

2024-06-10 09:25 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/data/coupon/remote/Mapper.kt
> +        LocalDate.parse(expirationDate) ?: throw IllegalArgumentException(INVALID_COUPON_DTO_PARAMETER),
> 어떤 부분에서 파싱 오류가 났는지 찾기 어렵지 않을까요?

설명을 예를 들어서 더 자세히 해보겠습니다.
동료 개발자가 개발하다가 INVALID_COUPON_DTO_PARAMETER exception 을 만났다고 생각해봅시다.
INVALID_COUPON_DTO_PARAMETER exception 은 다음과 같은 경우에 발생할 수 있습니다.

- buyQuantity 가 null 이어서 exception 이 발생
- getQuantity 가 null 이어서 exception 이 발생
- expirationDate 를 파싱하다가 exception 이 발생
- minimumAmount 가 null 이어서 exception 이 발생
- availableTime?.toAvailableTime() 가 null 이어서 exception 이 발생
- availableTime?.toAvailableTime() 가 왜 nulll 이면 exception 이 발생

동료 개발자가 INVALID_COUPON_DTO_PARAMETER exception 을 디버깅을 하려면,
위의 경우를 하나하나 모두 확인을 해보아야 합니다.
저 경우를 떠올릴 수 있는 것도 동료 개발자가 올리브의 코드를 모두 파악하고 있을 때에나 떠올릴 수 있는 것이고,
대부분의 경우는 어떤 경우에 exception 이 발생하는지 코드를 한줄한줄 전부 다 읽어봐야 할 것입니다.

심지어 코드를 전부 다 읽었다 하더라도 위의 경우를 다 떠올리지 못할 수도 있습니다.
저 조차도 혹시 더 많은 경우가 있지는 않을까 의심이 드네요.

exception 은 발생했을 때 무엇을 고쳐야할지 명확해야합니다.
협업을 할 때 충분히 일어날 수 있는 불편사항을 말씀드린 것이고,
어떻게 개선을 하면 좋을지는 올리브가 고민하셔서 동료가 편리하게끔 해주시기 바랍니다.

2024-06-10 15:17 UTC, ghojeong requested changes
올리브!
기존의 다른 피드백은 모두 훌륭하게 개선해주셔서,
아직 반영하지 못한 피드백을 다시 언급해봅니다.

[DTO 변환 exception 디버깅의 불편함](#discussion_r1632929739) 과
[Coupon 할인정책 유지보수의 불편함](#discussion_r1632311649) 이 
해결되어 있지 않습니다.

특히 할인정책 문제의 경우 Coupon 관련 객체설계를 통째로 다시해야할 만큼,
변경사항이 크리라 생각되는데 마지막인만큼 리팩토링에 욕심내보시기 바랍니다

2024-06-13 05:33 UTC, kimhm0728 commented
@ghojeong 
파이로 안녕하세요! 리뷰 반영 및 리팩터링 후 리뷰 요청드립니다.
벌써 마지막 리뷰 요청이네요.. 😢
레벨1에 이어서 레벨2도 파이로 덕분에 많이 배웠습니다.
질문 드릴 때마다 매번 상세히 답변 남겨주셔서 리뷰 받는 동안 정말 즐거웠습니다. 우선 순위와 시간 관리에 대한 조언도 감사했습니다. 👍

<br>

### 지난 리뷰 요청 때 반영하지 못한 사항들
- **[Coupon 할인정책 유지보수의 불편함](https://github.com/woowacourse/android-shopping-order/pull/79#discussion_r1632311649)**

반영 커밋 -> [74f4fe7](https://github.com/woowacourse/android-shopping-order/pull/79/commits/74f4fe71a400822164214d5c15928d2dfe4ac547)
(테스트 작성하면서 조금 변경된 부분이 있습니다. 위 커밋보다는 푸쉬된 전체 코드를 보시는 것이 리뷰에 편리할 것 같습니다.)

첨부해주신 링크 참고해서, 할인 정책과 할인 조건에 대한 인터페이스를 생성했습니다. 
**할인 정책(`DiscountPolicy`)** 은 "배송비 만큼 할인해 준다", "50% 할인해 준다" 등과 같이 "할인 금액"에 대한 것이고,
**할인 조건(`DiscountCondition`)** 은 "5만원 이상 구매 시 할인받을 수 있다", "3개 이상 구매 시 할인받을 수 있다" 등과 같이 "쿠폰을 적용할 수 있는가?"에 대한 것입니다.

기존에는 할인 정책과 할인 조건의 조합이 달라진다면, Coupon 구현체를 매번 새롭게 생성해야 한다는 단점이 있었습니다.
현재는 Coupon이 할인 정책을 프로퍼티로 갖고, 할인 정책에서는 할인 조건에 대한 리스트를 프로퍼티로 갖고 있습니다.
즉, 할인 정책이 달라지거나 할인 조건이 두 개 이상이 된다면 Coupon의 프로퍼티만 변경해주면 되기 때문에 유지보수성이 높아졌습니다. 👍👍

오랜만에 레벨1 이후로 도메인 설계를 제대로 해보니 재밌었습니다. 레벨2 부터는 도메인에 대한 큰 고민을 안 하고 코드를 작성한 것 같아 반성 중입니다.. ㅋㅋ 😢


- **[DTO 변환 exception 디버깅의 불편함](https://github.com/woowacourse/android-shopping-order/pull/79#discussion_r1632929739)**

반영 커밋 -> [e988fe7](https://github.com/woowacourse/android-shopping-order/pull/79/commits/e988fe760458c082aeada16b86d406d05f283c54)

Dto에서 파라미터가 null이 들어온 경우, 어떤 파라미터인지에 따라 예외 메시지를 다르게 수정했습니다.
또한 String을 LocalDate로 파싱하는 과정에서도 runCatching을 해주어서 예외 상황을 조금 더 구체화했습니다.
매핑 과정의 예외 메시지는 사용자가 아닌 개발자를 위한 메시지라고 생각해서, 예외 메시지에 어떤 객체에서 어떤 파라미터가 빠져있는지를 명시해주었습니다.

<br>

### 리뷰 반영 외 리팩터링 사항들 
- Retrofit Service interface를 하나만 구현했었는데, 호출하는 api가 많아질 경우 이 interface도 비대해질 것이라고 생각했습니다. 그래서 cart-items, products, coupon 등 도메인 별로 Service interface를 분리했습니다. [5416113](https://github.com/woowacourse/android-shopping-order/pull/79/commits/54161135585efaa209f8aec999b7405845c8d51a)
- 서버 url이나 user name, password를 하드 코딩하지 않고 local.properties로 이동했습니다. [d1aca53](https://github.com/woowacourse/android-shopping-order/pull/79/commits/d1aca53d7447ace6ab970973b329a972fc1eb251)
빌드 시 아래 문구 추가해주시면 됩니다!
```
base_url="http://54.180.95.212:8080"
user_name="kimhm0728"
password="password"
```
- 하나의 데이터에 대해 한 번만 observe하면 되는 이벤트들은 `Event` 객체로 감싸서 observe해주었습니다. 이 `Event`가 이미 소비된 데이터인지 확인하는 과정(`it.getContentIfNotHandled() ?: return@observe`)이 보일러 플레이트라고 생각해서, `SingleLiveData`로 변경했습니다! [1376647](https://github.com/woowacourse/android-shopping-order/pull/79/commits/1376647865f6303fc902545880510d6ed0cd509d)

<br>

마지막 리뷰도 잘 부탁드립니다. 감사합니다 🙇

2024-06-13 06:28 UTC, ghojeong approved these changes
올리브!
마지막까지 적극적인 학습 욕심을 내주셔서,
저도 함께 토론하고 의견 교류하는게 즐거웠습니다.

레벨2 완주하시느라 정말 고생 많으셨고,
우테코 과정의 완주를 응원하겠습니다!

2024-06-13 06:28 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/domain/model/DiscountCondition.kt
> +    ): Boolean
abstract fun 을 적극적으로 활용하는 형태로
할인 정책 관련 객체를 설계해주신 점 좋습니다. 👍

2024-06-13 06:28 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/data/coupon/remote/Mapper.kt
> +    val getQuantity = getQuantity ?: throw IllegalArgumentException(INVALID_GET_QUANTITY_PARAMETER)
예외 메시지를 구체화 해주셔서 좋습니다!
덕분에 디버깅할 때 바로 무엇이 잘못되었는지 알기 쉽겠네요.
DTO 변환에서의 문제는 백엔드와 협업할 때도,
누가 실수를 했는지 빨리 파악하기 위해서라도 저는 이렇게 구체적으로 예외처리 하는 편을 좋아합니다.

가령 백엔드에서 이상한 값을 보내거나 값을 보내지 않은 상황이 발생했는데,
크래시는 모바일에서 나다보니 모바일 탓이라고 다른 비개발자들이 생각하는 경우가 많아서요. ㅋㅋㅋㅋ

2024-06-13 06:28 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/data/remote/ProductService.kt
> +}
> 호출하는 api가 많아질 경우 이 interface도 비대해질 것이라고 생각했습니다. 
> 도메인 별로 Service interface를 분리했습니다

비대해질 위험성이 있다는 점 동의합니다.
그런면에서 도메인 별로 분리해주신게 무척 깔끔해보입니다. 👍 

다만 이렇게 되면 Repository 가 Service 객체를 참조해서 실행하는 모양새가 되는데,
올리브가 생각하시기에 Repository 와 Service 가 어떻게 다른지,
Layered Architecture 에 대해서 더 깊게 공부를 해보시면 좋을 것 같습니다.

2024-06-13 06:28 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/data/remote/RetrofitClient.kt
>              ).build()
local.properties로의 이동 좋습니다. 👍

2024-06-13 06:28 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/common/SingleLiveData.kt
> +    private val liveData = MutableLiveData<Event<T>>()
SingleLiveData 학습하고 적용하기 시간이 빠듯했을 텐데 대단합니다. 👍

2024-06-13 06:28 UTC, merged