[쇼핑 주문] 팡태 3, 4단계 미션 제출합니다.
woowacourse/android-shopping-order pull request #93
Opened 2024-06-10 08:33 UTC by Hevton

안녕하세요 말리빈!

이전에 남겨주셨던 피드백을 다 적용하면서, 데이터바인딩을 더 잘 활용하기 위해서
기존에 사용했던 아래와 같은 방식의 상태관리를 모두 제거하고
``` kotlin
sealed interface UiState<out T : Any> {
    data object Loading : UiState<Nothing>

    data class Success<out T : Any>(val data: T) : UiState<T>
}
```
아래와 같이, 단일 UiState를 사용하도록 로직을 모두 변경하였습니다.
``` kotlin
// Curation 에서 쓰이는 UiState 예시
data class CurationUiState(
    val cartProducts: List<CartProduct> = emptyList(),
    val isLoading: Boolean = true,
)
```

많은 변경을 진행했지만 아직 더 수정해보고 싶은 사항은 
1. Test 부분들
2. ViewModel의 로직을 도메인으로 더 감싸기
3. usecase 더 만들기

세 가지가 있네요..!

이번 스탭도 잘 부탁드립니다!!
```
계정 정보
user: hevton
password: password
```

2024-06-11 16:16 UTC, malibinYun requested changes
3, 4단계 미션 고생 많으셨어요!
여러 더 수정해보고 싶은 내용도 반영해보셔도 좋겠어요!
피드백 반영 후 다시 리뷰 요청 부탁드려요.

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/local/DefaultRecentProductDataSource.kt
> +class DefaultRecentProductDataSource(private val recentProductDao: RecentProductDao) : RecentProductDataSource {
이름만 보고는 데이터의 원천이 어느곳인지 알기 어려워보여요.
어느 곳에서 오는지 더 명확히 써보는 건 어떨까요?

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/datasource/cartItem/CartItemDataSource.kt
> +
DataSource 에서 retrofit의존성인 Response를 반환하는 건 올바른 형태일까요?
이 인터페이스로 LocalSource 구현체를 만들어야한다면 어떻게될까요?

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/dto/mapper/CouponMapper.kt
> +        CouponType.MIRACLESALE ->
non null 연산자 (!!)는 최대한 사용을 지양해보는 건 어떨까요?

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/dto/response/CouponResponse.kt
> +data class CouponResponse(
CouponResponse 자체를 sealed class로 만들어보는 건 어떨까요?
너무 어려우시다면 넘어가셔도 좋아요 :)

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/repository/CartItemRepositoryImpl.kt
> +            }
메서드 체이닝은 한 줄에 하나씩만 해보는 건 어떨까요?
어떤 장점이 생길까요? Exception과 연관지어 고민해보세요!

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/repository/CartItemRepositoryImpl.kt
> +        }
Result를 반환하니, runCatching을 사용하지 않고 구현해보는 건 어떨까요?

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/data/remote/repository/ProductRepositoryImpl.kt
> +
ProductPagingSource를 따로 가지고 있는 이유가 궁금하네요!
Page에 대한 객체등을 repository 단계에서 반환해주어야하는 역할일지 고민해보셔도 좋겠어요!

2024-06-11 16:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/domain/coupon/Coupon.kt
> +sealed class Coupon(
sealed interface를 활용해보는 건 어떨까요?

2024-06-13 04:20 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/local/DefaultRecentProductDataSource.kt
> +class DefaultRecentProductDataSource(private val recentProductDao: RecentProductDao) : RecentProductDataSource {
아하 동의합니다!! 사용처의 이름을 Prefix로 달아주었습니다!!

2024-06-13 04:22 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/datasource/cartItem/CartItemDataSource.kt
> +
이 부분을 인지하지 못하고 있었네요. 인터페이스 데이터소스에서 Retrofit의존성을 갖고 있으면 인터페이스로 정의한 의미가 없는 것 같습니다. 이를 Message 타입을 새로 정의해서 모두 리팩토링했습니다!

2024-06-13 04:30 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/dto/mapper/CouponMapper.kt
> +        CouponType.MIRACLESALE ->
추상화 과정에서 꼭 필요한 사항들에 대해서 지정해주었는데, 그래도 nullable 처리가 나은 것 같네요..!!
감사합니다 이를 반영했습니다.

2024-06-13 04:34 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/dto/response/CouponResponse.kt
> +data class CouponResponse(
sealed class로 만들까 고민을 했었는데, retrofit interface에서 받을 때 어떻게 처리해주어야할지 잘 모르겠더라구요 ㅜㅜ

2024-06-13 04:35 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/repository/CartItemRepositoryImpl.kt
> +            }
가독성으로 장점이 있을 것 같아 한 줄에 하나씩 처리하게 바꿨습니다!
Exception과 연관지어서는 어떤 말씀이신지 여쭤봐도 될까요?

2024-06-13 04:35 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/repository/CartItemRepositoryImpl.kt
> +        }
감사합니다 mapCatching을 활용해봤습니다!

2024-06-13 04:38 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/repository/ProductRepositoryImpl.kt
> +
데이터를 저장하는 Repository 단에서 페이지 정보를 저장하고 다뤄야 한다고 생각해서 이곳에서 처리해줬습니다..!
Paging3 라이브러리 흐름을 활용해보려했는데, 조언을 주실 수 있으실까요?
<img width="838" alt="스크린샷 2024-06-13 오후 1 37 47" src="https://github.com/woowacourse/android-shopping-order/assets/86276828/14a919bd-1b1b-4fa3-b922-a35a824c1802">

2024-06-13 04:42 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/domain/coupon/Coupon.kt
> +sealed class Coupon(
sealed class를 사용한 이유는 각 쿠폰마다 사용하는 공통 필드들을 추상화를 활용할 수 있겠다는 생각이었는데, 
대신에 각 쿠폰마다 개별적인 필드들은 nullable 이 요구되기 때문에 nullable 처리에 대한 단점을 가져가게 된 것 같습니다.
말리빈은 이 단점들을 생각하셔서 interface를 제시해주신걸까요?!!

2024-06-14 14:10 UTC, malibinYun approved these changes
마지막 미션까지 완수하시느라 고생 많으셨어요!
미션은 이만 마무리 하도록 하겠습니다 :)
지금까지 저와 소통했던 내용들이 앞으로 개발 하면서 도움이 되었으면 좋겠네요!
질문은 언제든 DM 으로 주셔도 좋아요 :)

2024-06-14 14:10 UTC, merged