[쇼핑 주문] 채드 3, 4 단계 미션 제출합니다.
woowacourse/android-shopping-order pull request #94
Opened 2024-06-10 08:33 UTC by dpcks0509

두루, 안녕하세요! 미션이 어려워서 기능구현하는데 시간이 오래걸려 제출이 늦었네요! 이번에도 좋은 리뷰 부탁드립니다!!

## 질문
PaymentViewModel 에서 
```kotlin
init {
        loadCartItems()
        loadCoupons()
    }
``` 
이렇게 초기에 구현하였는데 코루틴으로 인해 순서가 보장 되지 않아 loadCartItems()에서 cartItems에 값을 저장하기 전에 cartItems가 null인 채로 coupon에 대한 유효성 검증을 하게 되어서 쿠폰이 계속 빈상태로 되었습니다.

그래서 PaymentActivity에서
```kotlin
viewModel.cartItems.observe(this) {
            viewModel.loadCoupons()
        }
``` 
cartItems를 observe해서 cartItems에 값이 들어왔을때 loadCoupons()를 호출하도록 수정하였습니다.

다른 코루틴 비동기 처리 방식인 async, await 이나 Job, join을 이용한 방법 등을 생각도 해보았는데, 아직 코루틴에 익숙하지 않아서 적응을 해보지 못하였습니다. 이러한 방식이 괜찮은 방법인지, 그리고 추후에 다른 방법을 적용한다면 어떤 방식이 이러한 코루틴 순서를 보장하는데 사용하는 것이 좋을지 조언해주시면 감사하겠습니다!

[시연영상.webm](https://github.com/woowacourse/android-shopping-order/assets/102402485/9acd4a88-8b97-4685-b9b9-45e593037c99)

2024-06-10 14:20 UTC, Gyuil-Hwnag requested changes
채드 안녕하세요!

해당 미션 구현 고생 많으셨습니다!
미션 구현 정말 고생 많으셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다~
코루틴에 대한 개념을 잡기 위해서 질문 남겨주신 `PaymentViewModel` 부분에 생각해보면 좋을 키워들을 남겨두었습니다!

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
레벨2 안드로이드 마지막 미션 화이팅입니다💪

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/detail/DetailActivity.kt
> +    }
함수별 기능분리 정말 좋습니다!👍

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/detail/DetailActivity.kt
> +    private val viewModel: DetailViewModel by viewModels {
orgin 이라는 플래그 값은 어떤일을 할까요??🤔

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/detail/DetailActivity.kt
> +                        }
해당 내용을 origin 이라는 Flag 값을 사용하는 방법외에 다른 방법은 어떤 것들이 있을까요??🤔
origin 을 통해서 어떤 화면에서 현재 Detail 로 왔는지를 알려주려고 origin 을 사용하신 것이 맞을까요??
해당 동작처럼 하면 매번, 이전에 있던 Activity 는 인스턴스가 재생성이 될 것 같다는 생각이 듭니다!

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/detail/viewmodel/DetailViewModel.kt
> +                            )
해당 API들이 실패를 하게 되면 어떤 결과를 초래하게 될까요??🤔

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/detail/viewmodel/DetailViewModel.kt
> +    }
interface와 DataBinding의 활용 좋습니다~👍

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/home/viewmodel/HomeViewModel.kt
> +            }
에러의 활용 좋습니다~👍

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/order/OrderActivity.kt
> +
해당 내용도 Android Resource를 활용해보는 것은 어떤가 라는 생각이 듭니다!🤔

2024-06-10 14:20 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/payment/viewmodel/PaymentViewmodel.kt
> +    }
해당 내용이 PR에 질문으로 남겨주신 내용이군요!
우선 이 문제에 대해서 논의를 해보면서 채드한테 질문을 드릴게요~
- suspend 라는 키워드가 붙으면 어떤 동작을 할까요?
- 아래의 내용을 참고하면 `private fun loadCartItems() = viewModelScope.launch {}`와 같이 작성을 했을 때 커서를 대보면 `loadCartItems()` 해당 함수는 job 이라는 것을 알 수 있는데 이 `job`은 무엇일까요?
- 추가적으로 질문에 남겨주신 `job <- launch{}`, `async`는 어떤 차이점이 있을까요?

위의 질문만 생각해보더라도 채드의 코루틴에 대해서 많은 정리를 할 수 있을 것 같다는 생각이 듭니다!!

해결 방법은 아래와 같이 Job으로 묶어서 해결하는 방법이 있지만, suspend 라는 키워드에 대해서 잡고 가야 확실하게 의미가 있다는 생각이 듭니다!💪
~~~kotlin
    init {
        viewModelScope.launch {
            loadCartItems().join()
            loadCoupons()
        }
    }
...

    private fun loadCartItems() = viewModelScope.launch {
        val totalQuantity = cartRepository.getCartTotalQuantity().getOrNull() ?: 0
        cartRepository.getCartItems(0, totalQuantity, OrderViewModel.DESCENDING_SORT_ORDER)
            .onSuccess {
                _cartItems.value =
                    it.filter { cartItem -> cartItemIds.contains(cartItem.cartItemId) }
                _orderPrice.value = cartItems.value?.sumOf { cartItem -> cartItem.totalPrice }
                _deliveryPrice.value = DEFAULT_DELIVERY_PRICE
            }
    }
~~~

2024-06-11 07:39 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/ui/detail/DetailActivity.kt
> +    private val viewModel: DetailViewModel by viewModels {
어떤 화면에서 현재 Detail 로 왔는지를 알려주기 위해 선언하였습니다!

2024-06-11 12:32 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/ui/detail/DetailActivity.kt
> +                        }
origin으로 처리하는 방식을 삭제하고 onResume과 onRestart를 활용해 view를 업데이트 하도록 수정하였습니다!

2024-06-11 15:36 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/data/repository/CartRepositoryImpl.kt
>      }
map과 mapCatching은 동일한 행동을 하지만 예외 처리 방식에서 차이가 존재합니다.
map은 예외가 발생할 경우 바깥 블록에서 예외 처리를 하지만,
mapCatchiing에서는 내부 블록에서 예외 처리를 할 수 있습니다.

2024-06-11 16:10 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/ui/home/HomeActivity.kt
> +        productAdapter.submitProductViewItems(data.toList(), viewModel.canLoadMore.value ?: false)
ListAdapter에 새로운 아이템을 변경하였을때 제대로 반영되지 않았던 적이 있었는데 추가했다가 삭제를 깜빡한 것 같습니다! 삭제하였습니다!

2024-06-11 17:27 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/ui/detail/viewmodel/DetailViewModel.kt
> +                            )
실패할 경우 상품이 저장되지않아 어플이 원하는 동작을 제대로 하지 않을 것 같습니다. 
.onFailure { throw IllegalArgumentException() }를 통해 에러를 발생하도록 수정하였습니다!

2024-06-12 09:22 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/ui/payment/viewmodel/PaymentViewmodel.kt
> +    }
suspend는 다른 코루틴이 실행될때 잠시 일시정지하고 바로 실행되지 않도록 해주는 키워드입니다.
job은 코루틴에서 백그라운드에서 실행되는 하나의 작업 단위 의미합니다.
launch는 job을 리턴하고 aync는 deffered를 리턴합니다. Deffered는 Job을 상속한 클래스입니다.
그리고 launch는 결과값을 반환하지 않지만 async는 결과값을 반환합니다.

2024-06-12 09:24 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/ui/payment/viewmodel/PaymentViewmodel.kt
> +    }
```kotlin
 private fun loadCartItems() = viewModelScope.launch {
***
}
``` 

이런식으로 = viewModelScope.launch 을 사용해서 job을 반환하게 하는 것은 join을 하기 위한 함수에만 이렇게 선언하고 

```kotlin
fun loadCoupons() {
        viewModelScope.launch {
***
}
``` 
join을 하지 않는 나머지 함수들은 이런식으로 job을 반환하지 않도록 하는것이 좋을지, 아니면 모든 코루틴 관련된 함수를 = viewModelScope.launch 을 사용하여 job을 반환하도록 하는것이 좋으지 궁금합니다!

2024-06-13 13:12 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/detail/DetailActivity.kt
> +    private val viewModel: DetailViewModel by viewModels {
Flag 값을 사용하는 방법외에는 어떤 방법이 있을지 고민해봐도 좋을 것 같다는 생각이 듭니다🤔

2024-06-13 13:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/payment/viewmodel/PaymentViewmodel.kt
> +    }
개인 적으로는

2024-06-13 13:48 UTC, Gyuil-Hwnag approved these changes
채드 안녕하세요!
미션 너무 고생 많으셨습니다! 👏
리뷰 반영 정말 잘 해주셨어요💯

이번 미션을 통해서 Thread 부터 Coroutine 을 살펴보면서 비동기에 대해서 많은 부분을 살펴보왔는데 추후에 채드의 개발에 도움이 되었으면 좋겠습니다😀

다음 미션 진행을 위하여 해당 미션은 여기서 머지하도록 하겠습니다.
도움이 될만한 내용들 코멘트 달았으니 확인해보셔도 좋을 것 같습니다!

레벨2 마지막 미션까지 정말 너무나 고생 많으셨습니다~👍
궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
앞으로도 응원하겠습니다 💪

2024-06-13 13:48 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/mapper/Mapper.kt
> +}
Mapper 의 활용 좋습니다~👍

2024-06-13 13:48 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/order/OrderActivity.kt
> +
Android Resource의 활용 좋습니다~👍

2024-06-13 13:48 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/home/viewmodel/HomeViewModel.kt
>      }
`join()`을 활용 하도록 해주셨군요~👍
`join()`외에 Job 에는 여러 가지 함수들이 있으니 해당 내용들로 순서를 보장하도록 해보는 것도 추후 많은 도움이 될 것 같다는 생각이 듭니다!

2024-06-13 13:48 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/order/OrderActivity.kt
> +        observeViewModel()
기능별 함수 분리 좋습니다~👍

2024-06-13 13:48 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/order/cart/adapter/OrderBindingAdapter.kt
> +}
제네릭 타입의 활용 좋습니다~👍

2024-06-13 13:48 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/ui/order/viewmodel/OrderViewModel.kt
> +    }
사용 안하는 함수, 변수명에 대해서 정리도 해보면 구현이 깔끔해질 것 같다는 생각이 듭니다~👍

2024-06-13 13:48 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_payment.xml
> +            android:textStyle="bold"
해당 내용에 대해서 Android Resource 의 styles.xml 로 정의한다면, 동일한 형태의 Text 스타일로 제공을 할 수 있으며 추후 커스텀 폰트와 시스템 가이드를 사용할 때 활용하면 불필요한 반복되는 코드들을 줄여볼 수 있겠다는 생각이 듭니다~😀

2024-06-13 13:48 UTC, merged